begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id) values('7da32b3f-5801-4f2d-9911-ffdb25bed001'),('7da32b3f-5801-4f2d-9911-ffdb25bed002'),('7da32b3f-5801-4f2d-9911-ffdb25bed003');
insert into public.profiles(id,status) select id,'ACTIVE' from auth.users where id::text like '7da32b3f-%';
insert into public.user_roles(user_id,role_id) select u.id,r.id from auth.users u cross join public.roles r where u.id in ('7da32b3f-5801-4f2d-9911-ffdb25bed001','7da32b3f-5801-4f2d-9911-ffdb25bed002') and r.code='SUPER_ADMIN';
insert into public.branches(id,code,name) values('7da32b3f-5801-4f2d-9922-ffdb25bed001','HR-ATT-SYNTHETIC','Synthetic HR branch');
create temp table f(name text primary key,id uuid);grant all on f to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','7da32b3f-5801-4f2d-9911-ffdb25bed001',true);
insert into f select 'HQ',public.create_employee('HQ','2026-01-01','Synthetic HQ','Permanent','MONTHLY',null,null,null,'Test');
insert into f select 'ST',public.create_employee('ST','2026-01-01','Synthetic ST','Permanent','MONTHLY',null,null,null,'Test');
insert into f select 'LX',public.create_employee('LX','2026-01-01','Synthetic LX','Permanent','MONTHLY',null,null,null,'Test');
select is((select count(*) from public.employee_schedule((select id from f where name='HQ'),'2026-09-07','2026-09-07')),1::bigint,'Weekday has one afternoon shift');
select is((select count(*) from public.employee_schedule((select id from f where name='HQ'),'2026-09-12','2026-09-12')),2::bigint,'Saturday has two distinct shifts');
select is((select sum(scheduled_minutes) from public.employee_schedule((select id from f where name='HQ'),'2026-09-12','2026-09-12')),600::bigint,'Saturday preserves three plus seven hours');
select is((select scheduled_minutes from public.employee_schedule((select id from f where name='HQ'),'2026-09-13','2026-09-13')),420,'HQ Sunday expects seven hours');
select is((select schedule_state from public.employee_schedule((select id from f where name='ST'),'2026-09-13','2026-09-13')),'SCHEDULED_OFF','ST Sunday is rest');
select is((select scheduled_minutes from public.employee_schedule((select id from f where name='LX'),'2026-09-13','2026-09-13')),0,'LX rest does not create missing minutes');
select public.configure_employee_unit('ST','7da32b3f-5801-4f2d-9922-ffdb25bed001','Synthetic mapping');
insert into f select 'trip',public.request_employee_trip((select id from f where name='HQ'),'ST','7da32b3f-5801-4f2d-9922-ffdb25bed001','2026-09-13','2026-09-13','Synthetic trip');
select is((select scheduled_minutes from public.employee_schedule((select id from f where name='HQ'),'2026-09-13','2026-09-13')),420,'Unapproved trip has no effect');
select throws_ok($$select public.review_employee_trip((select id from f where name='trip'),'APPROVED','Self')$$,'P0001','Independent trip reviewer required','Trip maker cannot approve');
select set_config('request.jwt.claim.sub','7da32b3f-5801-4f2d-9911-ffdb25bed002',true);
select lives_ok($$select public.review_employee_trip((select id from f where name='trip'),'APPROVED','Checked')$$,'Independent trip approval');
select is((select scheduled_minutes from public.employee_schedule((select id from f where name='HQ'),'2026-09-13','2026-09-13')),240,'HQ branch trip Sunday expects four hours');
select is((select (ends_at at time zone 'Asia/Ho_Chi_Minh')::time from public.employee_schedule((select id from f where name='HQ'),'2026-09-13','2026-09-13')),'18:00'::time,'Trip evening is not missing work');
create function pg_temp.request(label text,day date,state text,arrival timestamptz default null,departure timestamptz default null,revision integer default 0) returns uuid language plpgsql as $$declare result uuid;begin
 perform set_config('request.jwt.claim.sub','7da32b3f-5801-4f2d-9911-ffdb25bed001',true);
 result:=public.request_employee_attendance((select id from f where name='HQ'),day,'PM',revision,state,arrival,departure,'Synthetic evidence',gen_random_uuid());insert into f values(label,result);return result;end$$;
create function pg_temp.approve(label text) returns uuid language plpgsql as $$begin
 perform set_config('request.jwt.claim.sub','7da32b3f-5801-4f2d-9911-ffdb25bed002',true);return public.review_employee_attendance((select id from f where name=label),'APPROVED','Checked evidence');end$$;
select pg_temp.request('worked','2026-09-07','WORKED');
select throws_ok($$select public.review_employee_attendance((select id from f where name='worked'),'APPROVED','Self')$$,'P0001','Independent attendance reviewer required','Attendance source is independently reviewed');
select pg_temp.approve('worked');
select is((select status from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-07'),'WORKED','Worked evidence approved');
select pg_temp.approve('worked');
select is((select count(*) from public.employee_attendance_entries where employee_id=(select id from f where name='HQ')),1::bigint,'Repeated approval does not duplicate');
select pg_temp.request('late','2026-09-08','LATE','2026-09-08T14:15:00+07','2026-09-08T21:00:00+07');select pg_temp.approve('late');
select is((select late_minutes from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-08'),15,'Late minutes preserved without salary formula');
select pg_temp.request('early','2026-09-09','EARLY_LEAVE','2026-09-09T14:00:00+07','2026-09-09T20:40:00+07');select pg_temp.approve('early');
select is((select early_minutes from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-09'),20,'Early departure minutes preserved');
select pg_temp.request('leave','2026-09-14','PAID_LEAVE');
select is((select count(*) from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-14'),0::bigint,'Pending paid leave creates no attendance evidence');
select pg_temp.request('rejected_leave','2026-09-15','PAID_LEAVE');
select set_config('request.jwt.claim.sub','7da32b3f-5801-4f2d-9911-ffdb25bed002',true);
select public.review_employee_attendance((select id from f where name='rejected_leave'),'REJECTED','Rejected evidence');
select is((select count(*) from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-15'),0::bigint,'Rejected paid leave creates no payable attendance');

select throws_ok($$select pg_temp.approve('leave')$$,'P0001','Configure approved leave quota before paid leave','No invented HQ leave quota');
select public.configure_employee_leave('HQ','Permanent',null,'2026-01-01','2026-12-31',210,'Explicit test quota');select pg_temp.approve('leave');
select is((select paid_leave_minutes from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-14'),210,'Paid leave constrained by explicit quota');
select is((select unpaid_leave_minutes from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-14'),210,'Excess leave is unpaid evidence');
reset role;
select is((hr_private.monthly_payroll_evidence((select id from f where name='HQ'),'2026-09-14','2026-09-14')->>'payable_minutes')::integer,210,'Leave workflow keeps canonical payroll payable minutes');
select throws_ok($$select hr_private.monthly_payroll_evidence((select id from f where name='HQ'),'2026-09-15','2026-09-15')$$,'P0001','Approved attendance required for every required shift','Rejected leave cannot feed payroll');
set local role authenticated;

select pg_temp.request('correct','2026-09-14','WORKED',null,null,1);select pg_temp.approve('correct');
select is((select count(*) from public.employee_attendance_entries where employee_id=(select id from f where name='HQ') and work_date='2026-09-14'),2::bigint,'Correction keeps original evidence');
select is((select entry_kind from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-14'),'MANUAL_CORRECTION','Current evidence is traced correction');
select throws_ok($$select public.request_employee_attendance((select id from f where name='HQ'),'2026-09-14','PM',1,'WORKED',null,null,'Stale',gen_random_uuid())$$,'P0001','Attendance changed; reload','Stale correction denied');
select throws_ok($$select public.request_employee_attendance((select id from f where name='ST'),'2026-09-13','PM',0,'UNAUTHORIZED_ABSENCE',null,null,'Wrong',gen_random_uuid())$$,'P0001','Scheduled rest cannot become absence or leave','Sunday rest cannot become absence');
select throws_ok($$select public.request_employee_attendance((select id from f where name='HQ'),'2099-01-01','PM',0,'WORKED',null,null,'Future',gen_random_uuid())$$,'P0001','Future attendance is not evidence','No fabricated future work');
select public.set_employee_version((select id from f where name='LX'),1,'2026-09-01','Synthetic LX','LX','Permanent','TERMINATED','MONTHLY',null,'Ended');
select is((select count(*) from public.employee_schedule((select id from f where name='LX'),'2026-09-07','2026-09-07')),0::bigint,'Ended employee has no current schedule');
select is((select count(*) from public.employee_schedule((select id from f where name='LX'),'2026-08-31','2026-08-31')),1::bigint,'Historical employment remains visible');
select pg_temp.request('trip_evidence','2026-09-13','BUSINESS_TRIP','2026-09-13T14:00:00+07','2026-09-13T18:00:00+07');select pg_temp.approve('trip_evidence');
select is((select early_minutes from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-13'),0,'Approved trip departure at eighteen is not early leave');
select pg_temp.request('unpaid','2026-09-10','UNPAID_LEAVE');select pg_temp.approve('unpaid');
select is((select unpaid_leave_minutes from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-10'),420,'Unpaid leave retains full scheduled minutes');
select pg_temp.request('absent','2026-09-11','UNAUTHORIZED_ABSENCE');select pg_temp.approve('absent');
select is((select status from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-11'),'UNAUTHORIZED_ABSENCE','Explicit absence evidence recorded');
select public.set_employee_version((select id from f where name='HQ'),1,'2026-09-07','Synthetic HQ','ST','Other group','ACTIVE','MONTHLY',null,'Later effective assignment audit');
select is((select unit_code from public.employee_schedule((select id from f where name='HQ'),'2026-09-07','2026-09-07')),'HQ','Previously recorded shift retains original unit after HR change');
select is((select count(*) from public.employee_schedule((select id from f where name='HQ'),'2026-09-07','2026-09-07')),1::bigint,'Snapshot overlay does not duplicate shift');
select pg_temp.request('historical_leave','2026-09-14','PAID_LEAVE',null,null,2);select pg_temp.approve('historical_leave');
select is((select paid_leave_minutes from public.employee_attendance_current where employee_id=(select id from f where name='HQ') and work_date='2026-09-14'),210,'Historical correction uses original employee group snapshot for quota');
select set_config('request.jwt.claim.sub','7da32b3f-5801-4f2d-9911-ffdb25bed003',true);
select is((select count(*) from public.employee_attendance_entries),0::bigint,'Unprivileged account cannot read attendance');
select is((select count(*) from public.employee_attendance_requests),0::bigint,'Unprivileged account cannot read another employee leave request');
select is((select count(*) from public.employee_leave_policies),0::bigint,'Unprivileged account cannot read leave entitlement configuration');
select throws_ok($$select * from public.employee_schedule((select id from f where name='HQ'),'2026-09-07','2026-09-07')$$,'P0001','Employee attendance denied','Unprivileged schedule RPC denied');
reset role;
select throws_ok($$update public.employee_attendance_entries set reason='Overwrite' where employee_id=(select id from f where name='HQ')$$,'P0001','Employee history is immutable','Original attendance immutable');
select ok(not has_table_privilege('service_role','public.employee_attendance_entries','INSERT'),'No service-role financial-source bypass');
select ok(not has_table_privilege('authenticated','public.employee_time_events','INSERT'),'Device integration not accidentally exposed');
select ok(not has_table_privilege('anon','public.employee_leave_policies','SELECT'),'Leave policies remain private to authorized HR admin');
select ok(not has_table_privilege('anon','public.employee_attendance_requests','SELECT'),'Leave requests introduce no anonymous read');
insert into public.user_roles(user_id,role_id,branch_id) select '7da32b3f-5801-4f2d-9911-ffdb25bed003',id,'7da32b3f-5801-4f2d-9922-ffdb25bed001' from public.roles where code='BRANCH_ADMIN';
set local role authenticated;
select set_config('request.jwt.claim.sub','7da32b3f-5801-4f2d-9911-ffdb25bed003',true);
select is((select count(*) from public.employee_attendance_requests),0::bigint,'Branch admin receives no new HR leave access from separate UI');
select throws_ok($$select public.configure_employee_leave('HQ',null,null,'2027-01-01','2027-12-31',420,'Unauthorized policy')$$,'P0001','Employee attendance denied','Branch assignment cannot grant global HR policy authority');
reset role;

select set_config('request.jwt.claim.sub','7da32b3f-5801-4f2d-9911-ffdb25bed002',true);
update public.profiles set status='INACTIVE' where id='7da32b3f-5801-4f2d-9911-ffdb25bed001';
set local role authenticated;
select set_config('request.jwt.claim.sub','7da32b3f-5801-4f2d-9911-ffdb25bed001',true);
select is((select count(*) from public.employee_attendance_entries),0::bigint,'Inactive administrator cannot read employee attendance');
select throws_ok($$select * from public.employee_schedule((select id from f where name='HQ'),'2026-09-07','2026-09-07')$$,'P0001','Employee attendance denied','Inactive administrator cannot invoke schedule');
select * from finish();rollback;
