begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id) values('ec000000-0000-0000-0000-000000000001'),('ec000000-0000-0000-0000-000000000002');
insert into public.profiles(id,status) values('ec000000-0000-0000-0000-000000000001','ACTIVE'),('ec000000-0000-0000-0000-000000000002','ACTIVE');
insert into public.user_roles(user_id,role_id) select 'ec000000-0000-0000-0000-000000000001',id from public.roles where code='SUPER_ADMIN';
insert into public.branches(id,code,name) values('f571bc1f-fabb-4b7b-9849-0e3c611afa0f','EMP-SYNTHETIC','Employee synthetic branch');
insert into public.teachers(id,teacher_code,full_name,user_id) values('8d243b76-0bb8-45f8-8ab5-d8fd2072d0a8','EMP-SYNTHETIC','Employee synthetic teacher','ec000000-0000-0000-0000-000000000002');
create temp table f(id uuid); grant all on f to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','ec000000-0000-0000-0000-000000000001',true);
select is((select count(*) from public.organization_units),3::bigint,'Three canonical organization units');
select lives_ok($$select public.configure_employee_unit('HQ','f571bc1f-fabb-4b7b-9849-0e3c611afa0f','Explicit synthetic mapping')$$,'Unit mapping explicit and audited');
select throws_ok($$select public.configure_employee_unit('ST','f571bc1f-fabb-4b7b-9849-0e3c611afa0f','Duplicate mapping')$$,'23505',null,'One branch cannot represent two units');
select throws_ok($$select public.create_employee('HQ','2026-01-01','Mismatch','Ops','MONTHLY',null,null,'8d243b76-0bb8-45f8-8ab5-d8fd2072d0a8','Wrong profile')$$,'P0001','Teacher/profile identity mismatch','Teacher identity must match linked profile');
insert into f select public.create_employee('HQ','2026-01-01','Employee synthetic','Operations','MONTHLY',null,'ec000000-0000-0000-0000-000000000002',null,'Verified identity');
select matches((select employee_code from public.employees where id=(select id from f)),'^VIBE-HQ-[0-9]{4,}$','Home-prefixed employee identity');
reset role;
select is((select count(*) from auth.users where id::text like 'ec000000-%'),2::bigint,'No auth account provisioned');
set local role authenticated;
select is((select unit_code from public.employee_directory where id=(select id from f)),'HQ','Initial assignment visible');
select throws_ok($$select public.create_employee('ST','2026-01-01','Duplicate','Operations','MONTHLY',null,'ec000000-0000-0000-0000-000000000002',null,'Duplicate')$$,'23505',null,'One employee per profile');
select lives_ok($$select public.set_employee_version((select id from f),1,'2026-02-01','Employee synthetic','ST','Operations','ACTIVE','PER_SESSION',null,'Transfer')$$,'Transfer records new version');
select is((select unit_code from public.employee_directory where id=(select id from f)),'ST','Current assignment follows effective transfer');
select matches((select employee_code from public.employees where id=(select id from f)),'^VIBE-HQ-','Transfer preserves home identity');
select is((select home_unit from public.employees where id=(select id from f)),'HQ','Home unit remains HQ');
select throws_ok($$select public.set_employee_version((select id from f),1,'2026-02-01','Wrong','LX','Operations','ACTIVE','MONTHLY',null,'Stale')$$,'P0001','Employee changed; reload before saving','Stale version rejected');
select throws_ok($$select public.set_employee_version((select id from f),2,'2025-01-01','Wrong','LX','Operations','ACTIVE','MONTHLY',null,'Backdate')$$,'P0001','Invalid effective date','No rewrite of older timeline');
select lives_ok($$select public.set_employee_version((select id from f),2,'2099-01-01','Employee synthetic','LX','Operations','TERMINATED','HOURLY',null,'Scheduled ending')$$,'Future employment end recorded');
select is((select unit_code from public.employee_directory where id=(select id from f)),'ST','Future version does not become current early');
select is((select employment_status from public.employee_directory where id=(select id from f)),'ACTIVE','Future termination not applied early');
select is((select end_date from public.employee_versions where employee_id=(select id from f) and version=3),'2099-01-01'::date,'End date is explicit');
select is((select count(*) from public.employee_versions where employee_id=(select id from f)),3::bigint,'All versions retained');
select ok((select bool_and(actor='ec000000-0000-0000-0000-000000000001'::uuid and reason<>'') from public.employee_audit where employee_id=(select id from f)),'Actor and reason audited');
select lives_ok($$select public.link_employee_identity((select id from f),null,null,'Unlink pending verification')$$,'Links can be corrected with audit');
select is((select count(*) from public.employee_audit where employee_id=(select id from f) and action='IDENTITY_LINK' and before_data->>'profile_id'='ec000000-0000-0000-0000-000000000002'),1::bigint,'Old identity link preserved in audit');
select is((select count(*) from public.user_roles where user_id='ec000000-0000-0000-0000-000000000002'),0::bigint,'Employment role never grants account privileges');
select set_config('request.jwt.claim.sub','ec000000-0000-0000-0000-000000000002',true);
select is((select count(*) from public.employees),0::bigint,'Unprivileged employee cannot read personnel');
select is((select count(*) from public.employee_directory),0::bigint,'Directory keeps RLS');
select throws_ok($$select public.link_employee_identity((select id from f),null,null,'Attack')$$,'P0001','Employee administration denied','Unauthorized RPC denied');
reset role;
select throws_ok($$update public.employees set home_unit='LX' where id=(select id from f)$$,'P0001','Employee identity is immutable','Database owner cannot rewrite employee code origin');
select throws_ok($$delete from public.employee_versions where employee_id=(select id from f)$$,'P0001','Employee history is immutable','Version history immutable');
select throws_ok($$update public.employee_audit set reason='Edited' where employee_id=(select id from f)$$,'P0001','Employee history is immutable','Audit immutable');
select ok(not has_table_privilege('authenticated','public.employees','INSERT'),'No direct insert');
select ok(not has_table_privilege('service_role','public.employee_versions','UPDATE'),'Service role cannot overwrite versions');
select ok(not has_function_privilege('anon','public.create_employee(text,date,text,text,text,uuid,uuid,uuid,text)','EXECUTE'),'Anonymous cannot provision employees');
select set_config('request.jwt.claim.sub','ec000000-0000-0000-0000-000000000001',true);
update public.profiles set status='INACTIVE' where id='ec000000-0000-0000-0000-000000000001';
set local role authenticated;
select set_config('request.jwt.claim.sub','ec000000-0000-0000-0000-000000000001',true);
select is((select count(*) from public.employees),0::bigint,'Inactive administrator cannot read');
select throws_ok($$select public.configure_employee_unit('HQ',null,'Attack')$$,'P0001','Employee administration denied','Inactive administrator cannot mutate');
select * from finish();
rollback;
