begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id) values('ee000000-0000-0000-0000-000000000001'),('ee000000-0000-0000-0000-000000000002'),('ee000000-0000-0000-0000-000000000003');
insert into public.profiles(id,status) select id,'ACTIVE' from auth.users where id::text like 'ee000000-%';
insert into public.user_roles(user_id,role_id) select u.id,r.id from auth.users u cross join public.roles r where u.id in ('ee000000-0000-0000-0000-000000000001','ee000000-0000-0000-0000-000000000002') and r.code='SUPER_ADMIN';
insert into public.branches(id,code,name) values('ee100000-0000-0000-0000-000000000001','LEGACY-A','Legacy A');
insert into public.curriculums(id,code,name) values('ee200000-0000-0000-0000-000000000001','LEGACY-PIANO','Legacy Piano');
insert into public.curriculum_levels(id,curriculum_id,code,name,sequence_no) values('ee300000-0000-0000-0000-000000000004','ee200000-0000-0000-0000-000000000001','LEGACY-G4','Grade 4',4);
insert into public.curriculum_subjects(level_id,family_code,code,name,completion_rule) values('ee300000-0000-0000-0000-000000000004','LEGACY','LEGACY-SUB','Subject','DIRECT_ASSESSMENT');
insert into public.courses(id,curriculum_id,level_id,code,name) values('ee400000-0000-0000-0000-000000000001','ee200000-0000-0000-0000-000000000001','ee300000-0000-0000-0000-000000000004','LEGACY-COURSE','Legacy course');
insert into public.classes(id,branch_id,course_id,code,name,class_type,capacity,status) values('ee500000-0000-0000-0000-000000000001','ee100000-0000-0000-0000-000000000001','ee400000-0000-0000-0000-000000000001','LEGACY-CLASS','Legacy class','GROUP',30,'ACTIVE');
insert into public.tuition_plans(id,code,name,duration_months) values('ee600000-0000-0000-0000-000000000001','LEGACY-PLAN','Legacy plan',1);
insert into public.tuition_plan_branch_prices(tuition_plan_id,branch_id,list_price,currency) values('ee600000-0000-0000-0000-000000000001','ee100000-0000-0000-0000-000000000001',5500000,'VND');
create temp table fixture(name text primary key,id uuid,payload jsonb);
grant all on fixture to authenticated;
insert into fixture(name,payload) values('source',jsonb_build_object(
 'legacy_reference','source-1','student_code','LEGACY-STUDENT-1','full_name','Legacy synthetic learner',
 'class_code','','curriculum_code','LEGACY-PIANO','level_code','LEGACY-G4',
 'started_at',(now() at time zone 'Asia/Ho_Chi_Minh')::date::text,
 'tuition_starts_on',(now() at time zone 'Asia/Ho_Chi_Minh')::date::text,
 'tuition_plan_code','LEGACY-PLAN','student_status','ACTIVE','tuition_status','ACTIVE',
 'currency','VND','discount_type','NONE','discount_value','0','final_amount','5500000','opening_paid_amount','3000000','opening_outstanding','2500000'));
set local role authenticated;
select set_config('request.jwt.claim.sub','ee000000-0000-0000-0000-000000000001',true);
insert into fixture(name,id) select 'batch',public.stage_legacy_batch('LEGACY-TEST','synthetic.csv',repeat('a',64),(now() at time zone 'Asia/Ho_Chi_Minh')::date,'ee100000-0000-0000-0000-000000000001',jsonb_build_array(payload)) from fixture where name='source';
insert into fixture(name,id) select 'row',id from public.migration_batch_rows where batch_id=(select id from fixture where name='batch');
select public.review_legacy_row((select id from fixture where name='row'),1,'MAP','Exact mapping',(select payload||'{"class_code":"LEGACY-CLASS"}'::jsonb from fixture where name='source'));
select public.review_legacy_row((select id from fixture where name='row'),2,'IDENTITY','Checked');
select public.review_legacy_row((select id from fixture where name='row'),2,'ACADEMIC','Checked');
select set_config('request.jwt.claim.sub','ee000000-0000-0000-0000-000000000002',true);
select public.review_legacy_row((select id from fixture where name='row'),2,'FINANCE','Independent check');
select public.import_legacy_row((select id from fixture where name='row'),2);
insert into fixture(name,id) select 'opening',id from public.opening_receivables where migration_row_id=(select id from fixture where name='row');
create function pg_temp.balance() returns numeric language sql as $$select outstanding_balance from public.opening_receivable_balances where id=(select id from fixture where name='opening')$$;
create function pg_temp.make(label text,op text,target uuid,details jsonb) returns uuid language plpgsql as $$declare rid uuid; begin
 perform set_config('request.jwt.claim.sub','ee000000-0000-0000-0000-000000000001',true);
 rid:=public.request_financial_action(op,target,details,'Synthetic regression',gen_random_uuid());
 insert into fixture(name,id) values(label,rid);return rid;end $$;
create function pg_temp.approve(label text) returns uuid language plpgsql as $$begin
 perform set_config('request.jwt.claim.sub','ee000000-0000-0000-0000-000000000002',true);
 return public.approve_financial_action((select id from fixture where name=label),'Independent regression check');end $$;
select is(pg_temp.balance(),2500000::numeric,'Opening debt starts at 2.5m');
select is((select count(*) from public.finance_cash_ledger where branch_id='ee100000-0000-0000-0000-000000000001'),0::bigint,'Pre-cutover settlement creates no cash');
insert into fixture(name,id) select 'payment',public.create_payment(student_id,branch_id,1000000,'VND','CASH',now(),'OPENING-TEST','Synthetic post-cutover receipt') from public.opening_receivables where id=(select id from fixture where name='opening');
insert into fixture(name,id) select 'allocation',public.allocate_payment_to_opening((select id from fixture where name='payment'),(select id from fixture where name='opening'),1000000);
select is(pg_temp.balance(),1500000::numeric,'Payment allocation reduces opening debt');
select is(public.allocate_payment_to_opening((select id from fixture where name='payment'),(select id from fixture where name='opening'),1000000),(select id from fixture where name='allocation'),'Identical allocation retry returns original');
select is((select count(*) from public.payment_allocations where opening_receivable_id=(select id from fixture where name='opening')),1::bigint,'No duplicate allocation');
select is((select cash_received from public.branch_finance_summary where branch_id='ee100000-0000-0000-0000-000000000001'),1000000::numeric,'Actual receipt enters existing cash summary');
select is((select billed_amount from public.branch_finance_summary where branch_id='ee100000-0000-0000-0000-000000000001'),0::numeric,'Old debt collection creates no billed revenue');
select is((select new_revenue_from_collection from public.opening_receivable_balances where id=(select id from fixture where name='opening')),0::numeric,'Opening collection has zero new revenue');
select is((select count(*) from public.invoices where branch_id_snapshot='ee100000-0000-0000-0000-000000000001'),0::bigint,'Collection creates no duplicate invoice');
select throws_ok($$select public.allocate_payment_to_opening((select id from fixture where name='payment'),(select id from fixture where name='opening'),500000)$$,'P0001','Existing allocation amount differs','Retry cannot overwrite original allocation');
select pg_temp.make('increase','OPENING_RECEIVABLE_CORRECTION',(select id from fixture where name='opening'),'{"corrected_amount":6000000}');
select throws_ok($$select public.approve_financial_action((select id from fixture where name='increase'),'Self')$$,'P0001','Maker cannot approve own financial request','Correction maker cannot self approve');
select is(pg_temp.balance(),1500000::numeric,'Pending correction changes no debt');
select lives_ok($$select pg_temp.approve('increase')$$,'Independent checker posts increase');
select is(pg_temp.balance(),2000000::numeric,'Positive correction raises carried debt');
select is((select amount from public.opening_receivables where id=(select id from fixture where name='opening')),5500000::numeric,'Original opening amount immutable');
select is((select delta from public.opening_receivable_corrections where id=(select id from fixture where name='increase')),500000::numeric,'Correction stores exact delta');
select ok((select maker_user_id<>checker_user_id and migration_batch_id=(select id from fixture where name='batch') and source_reference='source-1' from public.opening_receivable_corrections where id=(select id from fixture where name='increase')),'Correction links source and independent identities');
select is(pg_temp.approve('increase'),(select id from fixture where name='increase'),'Approval retry is idempotent');
select pg_temp.make('decrease','OPENING_RECEIVABLE_CORRECTION',(select id from fixture where name='opening'),'{"corrected_amount":5750000}');
select pg_temp.approve('decrease');
select is(pg_temp.balance(),1750000::numeric,'Negative correction reduces carried debt');
select is((select cash_received from public.branch_finance_summary where branch_id='ee100000-0000-0000-0000-000000000001'),1000000::numeric,'Corrections do not create cash');
select lives_ok($$select pg_temp.make('credit','OPENING_RECEIVABLE_CORRECTION',(select id from fixture where name='opening'),'{"corrected_amount":2000000}')$$,'Excess correction request is allowed; not posted until approved');
select pg_temp.make('refund','REFUND',(select id from fixture where name='payment'),jsonb_build_object('amount',400000,'refunded_at',now()));
insert into fixture(name,id) values('refund-result',pg_temp.approve('refund'));
select pg_temp.make('refund-allocation','ALLOCATE_REFUND',(select id from fixture where name='refund-result'),jsonb_build_object('amount',400000,'payment_allocation_id',(select id from fixture where name='allocation')));
select lives_ok($$select pg_temp.approve('refund-allocation')$$,'Existing refund allocation supports opening target');
select is(pg_temp.balance(),2150000::numeric,'Allocated refund restores opening debt');
select pg_temp.make('void-refund','VOID_REFUND',(select id from fixture where name='refund-result'),'{}');
select pg_temp.approve('void-refund');
select is(pg_temp.balance(),1750000::numeric,'Voiding refund reinstates allocation');
select pg_temp.make('void-payment','VOID_PAYMENT',(select id from fixture where name='payment'),'{}');
select pg_temp.approve('void-payment');
select is(pg_temp.balance(),2750000::numeric,'Voiding payment restores corrected debt');
select is((select correction_amount from public.opening_receivable_balances where id=(select id from fixture where name='opening')),250000::numeric,'Correction sum preserved after reversals');
select is((select amount_difference+paid_difference+outstanding_difference from public.migration_reconciliation where row_id=(select id from fixture where name='row')),0::numeric,'Original import reconciliation remains exact');
select is((select count(*) from public.financial_approval_events where request_id=(select id from fixture where name='increase')),3::bigint,'Requested approved and posted events retained');
select ok(not has_table_privilege('authenticated','public.opening_receivable_corrections','UPDATE'),'No client correction mutation privilege');
select ok(not has_table_privilege('service_role','public.opening_receivables','INSERT'),'No direct service opening posting');
select pg_temp.make('legacy-excess','OPENING_RECEIVABLE_CORRECTION',(select id from fixture where name='opening'),'{"corrected_amount":2000000}');
select lives_ok($$select pg_temp.approve('legacy-excess')$$,'Pre-cutover excess correction is retained without inventing a payment');
select is(pg_temp.balance(),0::numeric,'Historical excess also leaves zero receivable');
select is((select remaining_credit from public.customer_credit_balances where correction_id=(select id from fixture where name='legacy-excess')),1000000::numeric,'Historical settlement credit remains visible');
select ok((select payment_id is null and settlement_id is not null from public.customer_credits where correction_id=(select id from fixture where name='legacy-excess')),'Historical credit traces settlement, not fabricated cash');
select throws_ok($$select public.request_financial_action('REFUND_CUSTOMER_CREDIT',(select id from public.customer_credits where correction_id=(select id from fixture where name='legacy-excess')),jsonb_build_object('amount',100,'refunded_at',now()),'No invented source payment',gen_random_uuid())$$,'P0001','Legacy settlement credit requires source payment review','Historical credit stays pending source review');
select set_config('request.jwt.claim.sub','ee000000-0000-0000-0000-000000000003',true);
select throws_ok($$select public.allocate_payment_to_opening((select id from fixture where name='payment'),(select id from fixture where name='opening'),1)$$,'P0001','Unauthorized','Unprivileged allocation denied');
select is((select count(*) from public.opening_receivable_corrections),0::bigint,'Unprivileged correction read denied');
reset role;
select throws_ok($$update public.opening_receivables set amount=1 where id=(select id from fixture where name='opening')$$,'P0001','Financial approval history is immutable','Original amount cannot be directly rewritten even by table owner');
select throws_ok($$delete from public.opening_settlements where receivable_id=(select id from fixture where name='opening')$$,'P0001','Financial approval history is immutable','Original settlement cannot be deleted');
select throws_ok($$update public.opening_receivable_corrections set delta=1 where id=(select id from fixture where name='increase')$$,'P0001','Financial approval history is immutable','Posted correction cannot be rewritten');
select * from finish();
rollback;
