begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
select is((select count(*) from information_schema.table_privileges where table_schema='public' and grantee in('anon','PUBLIC')),0::bigint,'No anonymous business relation grants');
select is((select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='S' and (has_sequence_privilege('anon',c.oid,'USAGE') or has_sequence_privilege('anon',c.oid,'UPDATE') or has_sequence_privilege('anon',c.oid,'SELECT'))),0::bigint,'Anonymous cannot inspect or advance business sequences');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prosecdef and has_function_privilege('anon',p.oid,'EXECUTE')),0::bigint,'No anonymous SECURITY DEFINER execution');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prosecdef and not (coalesce(p.proconfig @> array['search_path=public, pg_temp'],false) or coalesce(p.proconfig @> array['search_path=pg_catalog, pg_temp'],false))),0::bigint,'Every public SECURITY DEFINER pins trusted search_path');
select is((select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in('r','p') and has_table_privilege('authenticated',c.oid,'SELECT') and not c.relrowsecurity),0::bigint,'Authenticated business tables enforce RLS');
select is((select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='v' and has_table_privilege('authenticated',c.oid,'SELECT') and not coalesce(c.reloptions @> array['security_invoker=true'],false)),0::bigint,'Authenticated views preserve caller privileges');
select ok(not has_schema_privilege('anon','public','CREATE'),'Anonymous cannot replace trusted schema objects');
select ok(not has_schema_privilege('authenticated','public','CREATE'),'Authenticated cannot replace trusted schema objects');
select is((select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind in('r','p') and has_table_privilege('authenticated',c.oid,'TRUNCATE')),0::bigint,'Authenticated cannot bypass RLS with TRUNCATE');
set local role anon;
select throws_ok('select id from public.students','42501','permission denied for table students','Anonymous student query denied at privilege boundary');
select throws_ok('select * from public.branch_finance_summary','42501','permission denied for view branch_finance_summary','Anonymous finance query denied at privilege boundary');
reset role;
select ok(has_table_privilege('authenticated','public.students','SELECT'),'Authenticated student query privilege retained; RLS decides rows');
select ok(has_table_privilege('authenticated','public.branch_finance_summary','SELECT'),'Authenticated finance query privilege retained; RLS decides rows');
create table public.security_catalogue_fixture(id bigint generated always as identity);
select ok(not has_table_privilege('anon','public.security_catalogue_fixture','SELECT'),'New postgres migration tables do not inherit anonymous select');
select ok(not has_table_privilege('anon','public.security_catalogue_fixture','INSERT'),'New postgres migration tables do not inherit anonymous write');
select ok(not has_sequence_privilege('anon','public.security_catalogue_fixture_id_seq','USAGE'),'New postgres migration sequences do not inherit anonymous usage');
select * from finish();
rollback;
