/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript')
const m={exports:{}};new Function('module','exports',ts.transpileModule(fs.readFileSync('lib/learning/aural.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m,m.exports)
const {parseAuralDraft,auralModules}=m.exports
const asset=()=>({id:'a0000000-0000-4000-8000-000000000001',sha256:'a'.repeat(64),mime:'audio/wav',durationMs:5000,provenance:'Synthetic metadata fixture; no actual audio or reviewed content'})
const draft=()=>({schema:1,state:'DRAFT',module:'1A',type:'AURAL_METRE_CHOICE',prompt:'Synthetic fixture',maxPlays:2,stimuli:[{role:'ORIGINAL',asset:asset()}],response:{kind:'CHOICE',options:['Duple','Triple']}})
test('Aural module catalogue preserves approved Grade 1–3 structure',()=>{assert.deepEqual(auralModules.map(m=>m[0]),['1A','1B','1C','1D','2A','2B','2C','2D','3A','3B','3C','3D']);assert.equal(auralModules[11][1],'Musical Features + Tempo + Tonality')})
test('explicit draft roundtrip retains opaque asset identity and replay policy',()=>{assert.deepEqual(parseAuralDraft(draft()),draft())})
test('change detection requires an ordered original/comparison pair',()=>{const d={...draft(),module:'2C',type:'AURAL_CHANGE_DETECTION'};assert.throws(()=>parseAuralDraft(d));d.stimuli.push({role:'COMPARISON',asset:{...asset(),id:'a0000000-0000-4000-8000-000000000002'}});assert.equal(parseAuralDraft(d).stimuli.length,2);d.stimuli.reverse();assert.throws(()=>parseAuralDraft(d))})
test('tonality is restricted to approved Grade 3D scope',()=>{const d={...draft(),type:'AURAL_TONALITY_CHOICE'};for(const moduleCode of ['1D','2D','3A','4D'])assert.throws(()=>parseAuralDraft({...d,module:moduleCode}));assert.equal(parseAuralDraft({...d,module:'3D'}).module,'3D')})
test('echo requires bounded recording and private manual rubric, never an automatic score',()=>{const d={...draft(),module:'1B',type:'AURAL_ECHO_RECORDING',response:{kind:'RECORDING',maxDurationMs:30000,rubric:'Synthetic manual rubric'}};assert.equal(parseAuralDraft(d).response.kind,'RECORDING');for(const response of [{kind:'CHOICE',options:['pass','fail']},{...d.response,rubric:''},{...d.response,score:100},{...d.response,maxDurationMs:Infinity}])assert.throws(()=>parseAuralDraft({...d,response}))})
test('metadata cannot smuggle public URLs, object paths, answer keys or approval',()=>{for(const key of ['url','path','signedUrl']){const d=draft();d.stimuli[0].asset[key]='https://example.invalid/private';assert.throws(()=>parseAuralDraft(d))}for(const change of [{state:'APPROVED'},{key:'Duple'},{score:100},{reviewer:'forged'}])assert.throws(()=>parseAuralDraft({...draft(),...change}))})
test('invalid media metadata, missing policies, oversized limits and duplicate choices fail closed',()=>{for(const maxPlays of [undefined,0,101,1.5,'2'])assert.throws(()=>parseAuralDraft({...draft(),maxPlays}));for(const change of [{sha256:'bad'},{mime:'text/html'},{durationMs:0},{durationMs:600001},{provenance:''}]){const d=draft();Object.assign(d.stimuli[0].asset,change);assert.throws(()=>parseAuralDraft(d))}assert.throws(()=>parseAuralDraft({...draft(),response:{kind:'CHOICE',options:['same',' same ']}}))})
