const assert = require('node:assert/strict')
const fs = require('node:fs')

const page = fs.readFileSync('app/admin/hr/expenses/page.tsx', 'utf8')
const selfService = fs.readFileSync('app/admin/hr/expenses/SelfServiceView.tsx', 'utf8')
const actions = fs.readFileSync('app/admin/hr/expenses/actions.ts', 'utf8')
const data = fs.readFileSync('app/admin/hr/expenses/data.ts', 'utf8')
const model = fs.readFileSync('app/admin/hr/expenses/model.ts', 'utf8')

assert.ok(!page.includes('type="file"') && !selfService.includes('type="file"'), 'V2 page must not upload an evidence file')
assert.match(page, /evidenceCount/, 'Chứng từ column counts stored evidence lines')
assert.match(selfService, /list="expense-category-suggestions"/, 'category input uses optional suggestions')
assert.match(selfService, /name="category_name"/, 'category remains a free text input')
assert.match(model, /Phí hành lý|Phí hội nghị|categorySuggestions/, 'category suggestions are presentation-only')
assert.match(selfService, /\['DRAFT', 'RETURNED'\]/, 'draft and returned claims expose editing')
assert.match(selfService, /claim\.status === 'SUBMITTED'/, 'submitted workflow renders separately')
assert.match(selfService, /!owner/, 'review controls require a different actor in the UI')
assert.match(selfService, /Chưa có bằng chứng chi trả/, 'approved is not presented as paid')
assert.match(selfService, /payroll_posting\.status/, 'detail posting state comes from the database snapshot')
assert.match(data, /list_employee_expense_claims_v2/, 'list uses the bounded database RPC')
assert.match(actions, /create_employee_expense_claim_v2/, 'V2 creation uses the V2 RPC')
assert.match(actions, /save_employee_expense_claim_item_v2/, 'V2 items never use the legacy line RPC')
assert.ok(!actions.includes('save_employee_expense_claim_line'), 'legacy save RPC is absent from V2 actions')
assert.match(page, /placeholder="Tên, mã nhân viên, mục đích\.\.\."/, 'search box keeps its field hint')
assert.equal((page.match(/placeholder/gi) || []).length, 1, 'the only placeholder is the search hint')
assert.ok(!/\bmock\b|\bdemo\b/i.test(page + selfService), 'production page contains no fake-data marker')
assert.match(actions, /Không xác nhận được trạng thái ghi dữ liệu/, 'uncertain writes require reload and reconciliation')

console.log('Expense Claim V2 UI/action source contract: PASS')
