const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = 'app/admin/finance/management-report/charts'
const trend = fs.readFileSync(path.join(root, 'FinancialTrendChart.tsx'), 'utf8')
const opex = fs.readFileSync(path.join(root, 'OperatingExpenseChart.tsx'), 'utf8')
const branch = fs.readFileSync(path.join(root, 'BranchComparisonChart.tsx'), 'utf8')
const scale = fs.readFileSync(path.join(root, 'scale.ts'), 'utf8')
const charts = [trend, opex, branch, scale].join('\n')

assert.match(trend, /report\.trend_12_months/, 'C01 chart uses canonical trend')
assert.match(trend, /points\.forEach|points\.map/, 'C02 renders the returned month points')
assert.doesNotMatch(trend, /Array\.from\(\{ length: 12/, 'C02 does not invent month points')
assert.match(trend, /centsValue === null/, 'C03 null is not plotted')
assert.doesNotMatch(trend, /\?\? 0|value \|\| 0|as 0/, 'C03 null is not replaced with zero')
assert.match(trend, /PARTIAL/, 'C04 partial marker exists')
assert.match(trend, /Chưa đầy đủ/, 'C04 partial stays visible as text')
assert.match(scale, /if \(high < ZERO\) high = ZERO/, 'C05 zero baseline includes negative results')
assert.match(trend, /operating_result/, 'C05 operating result is a plotted series')
assert.doesNotMatch(charts, /personnel_expense \+|travel.*\+|operating_expense \+/, 'C06 no total expense sum')
assert.doesNotMatch(charts, /Total Expense|Tổng chi phí/, 'C06 no total expense label')
assert.doesNotMatch(charts, /supabase|\.from\(|get_financial_management_report|operating_expense_records|invoices|payments/, 'C07 no direct finance query')
assert.match(opex, /operating_expense\.by_category/, 'C08 opex chart uses categories')
assert.match(opex, /planned === null \|\| row\.planned === undefined \? null/, 'C09 null plan is not a zero bar')
assert.match(opex, /planned_status === 'PARTIAL'/, 'C10 partial plan is visible')
assert.match(opex, /Chưa đầy đủ/, 'C10 partial plan text')
assert.doesNotMatch(opex, /recorded_amount\s*-|actual\s*-|planned_known_amount\s*-/, 'C11 chart does not calculate variance')
assert.match(opex, /opexCategoryLabel/, 'C12 category label helper, unknown codes fall through')
assert.match(opex, /Thực tế đã ghi nhận/, 'C13 recorded wording')
assert.doesNotMatch(opex, /Đã chi/, 'C13 recorded is not labelled paid')
assert.match(branch, /report\.branches/, 'C14 branch chart uses canonical branches')
assert.match(branch, /row\.branch_name/, 'C15 branch names come from the report')
assert.doesNotMatch(branch, /Local Expense|Cần Thơ|Finance Report A/, 'C15 no hard-coded branch names')
assert.match(branch, /PARTIAL/, 'C16 partial branch marker')
assert.match(branch, /Chưa đầy đủ/, 'C16 partial text')
assert.doesNotMatch(charts, /management_result|Kết quả quản trị/, 'C17 no management result chart')
assert.doesNotMatch(charts, /\.reduce\(|branches\.map\([^)]*=>[^)]*\+/, 'C18 no client consolidated sum')
assert.doesNotMatch(charts, /Lợi nhuận|lợi nhuận|Net Profit|Profit Chart/, 'C19 no profit wording')
assert.doesNotMatch(charts, /Doanh thu tháng|P&L Complete/, 'C20 no false complete revenue title')
assert.match(trend, /XU HƯỚNG 12 THÁNG/, 'chart A title')
assert.match(opex, /CHI PHÍ VẬN HÀNH/, 'chart B title')
assert.match(branch, /SO SÁNH CHI NHÁNH/, 'chart C title')
assert.match(scale, /if \(value === null \|\| value === undefined\) return null/, 'scale keeps null')

console.log('Financial chart contract: PASS')
