const assert = require('node:assert/strict')
const fs = require('node:fs')

const page = fs.readFileSync('app/documents/finance/management-report/page.tsx', 'utf8')
const document = fs.readFileSync('app/documents/finance/management-report/FinancialManagementReportDocument.tsx', 'utf8')
const button = fs.readFileSync('app/documents/finance/management-report/PrintFinancialReportButton.tsx', 'utf8')
const printCss = fs.readFileSync('app/documents/finance/management-report/financial-report-print.css', 'utf8')
const sharedPrint = fs.readFileSync('app/documents/print.css', 'utf8')
const presentation = fs.readFileSync('app/admin/finance/management-report/presentation.ts', 'utf8')
const tower = fs.readFileSync('app/admin/finance/management-report/FinanceControlTower.tsx', 'utf8')
const report = document + page

assert.match(document, /FinancialManagementReportDocument/, 'R01 dedicated document component')
assert.match(page, /loadFinanceControlTower/, 'R02 document page uses the canonical loader')
assert.equal(page.match(/loadFinanceControlTower\(/g).length, 1, 'R02 one loader call inside the request cache')
assert.match(page, /cache\(/, 'R02 metadata and page share one cached load')
assert.doesNotMatch(report, /\.from\(|\.rpc\(|supabase/, 'R03 document does not query finance tables')
assert.doesNotMatch(document, /revenue\.value\s*[-+]|personnel_expense\.value\s*[-+]|recorded_amount\s*-|total_in_integrated\.value\s*[-+]/, 'R04-R07 no document formulas')
assert.doesNotMatch(document, /branches\.reduce|by_branch\.reduce/, 'R08 no branch total calculation')
assert.match(document, /revenueTitle/, 'R09 revenue label uses the partial-aware helper')
assert.match(presentation, /Doanh thu xác định được/, 'R09 partial revenue wording')
assert.match(document, /managementUnavailable \? '—'/, 'R10 null management result stays blank')
assert.match(document, /Chưa đủ nguồn dữ liệu để kết luận kết quả quản trị sau chi phí tài chính/, 'R10 no profit conclusion')
assert.doesNotMatch(document, /Lợi nhuận|lợi nhuận|Báo cáo tài chính pháp định/, 'R10/R22 no profit or statutory claim')
assert.match(document, /CHI PHÍ VẬN HÀNH/, 'R11 dedicated opex section')
assert.match(document, /opexVarianceText/, 'R12 variance comes from the shared canonical display rule')
assert.match(presentation, /planned_status !== 'AVAILABLE'/, 'R12 incomplete plan variance is blank')
assert.match(document, /không đồng nghĩa đã thanh toán/, 'R13 recorded opex is not paid')
assert.match(document, /opex_cash_out/, 'R13 opex cash row remains')
assert.match(document, /Công nợ hiện tại/, 'R14 current receivable label')
assert.match(document, /Công nợ cuối kỳ/, 'R15 month-end row exists')
assert.match(document, /Chưa hỗ trợ ảnh chụp công nợ cuối kỳ/, 'R15 month-end note')
assert.match(document, /Dư nợ vay/, 'R16 loan row exists')
assert.match(document, /Chưa có nguồn dữ liệu khoản vay được xác nhận/, 'R16 loan note')
assert.match(document, /trend_12_months\.map/, 'R17 12-month table uses canonical trend')
assert.match(document, /FinancialTrendChart/, 'R17 12-month chart component')
assert.match(document, /report\.branches\.map/, 'R18 branch table uses canonical branches')
assert.match(document, /CHẤT LƯỢNG DỮ LIỆU & PHẠM VI BÁO CÁO/, 'R19 source quality section')
assert.match(document, /source_status\.map/, 'R19 renders source_status')
assert.match(document, /generated_at/, 'R20 generated_at is displayed')
assert.match(document, /BÁO CÁO TÀI CHÍNH QUẢN TRỊ/, 'R21 official title')
assert.match(printCss, /@media print/, 'R23 print stylesheet')
assert.match(sharedPrint, /@page/, 'R23 page rule from the document print system')
assert.match(printCss, /document-actions/, 'R24 print hides document controls')
assert.doesNotMatch(document, /AdminNavigation|Đăng xuất/, 'R24 no admin navigation in the document')
assert.match(button, /window\.print/, 'R25/E04 print action is browser print')
assert.match(button, /document\.title = title/, 'E10 print uses the PDF-friendly document title')
assert.match(page, /PrintFinancialReportButton title=\{title\}/, 'E10 title is set from the loaded report')
assert.doesNotMatch(report + button, /pdfkit|puppeteer|Download PDF|server-generated PDF/, 'R25 no fake server PDF')

assert.match(tower, /Xuất báo cáo/, 'E01 export button')
assert.match(tower, /financialReportHref\(month, branchId, currency\)/, 'E02 export keeps month, branch, and currency')
assert.match(page, /FinancialManagementReportDocument report=\{data\.report\}/, 'E03 document renders the loaded canonical report')
assert.match(page, /generateMetadata/, 'E10 document title metadata')
assert.match(presentation, /VIBE-Financial-Management-Report-/, 'E10 PDF-friendly document title')
assert.match(printCss, /fm-report figure > svg/, 'E06 chart SVGs remain in the print layout')
assert.match(printCss, /break-inside: avoid/, 'E07 chart blocks avoid splitting')

console.log('Financial report document contract: PASS')
