/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict')
const {harness,id,redirected}=require('./helpers/finance-operations.cjs')
const sale={action:'SALE',request:id(1),unit:id(2),model:id(3),price:'1200000',currency:'VND',reason:'Synthetic sale evidence'}
test('instrument mutation requires authenticated admin',async()=>{const h=harness({},null,false);const u=await redirected(h.load('../instruments/actions.ts').instrumentAction,sale);assert.equal(u.pathname,'/login');assert.equal(h.calls.length,1)})
test('instrument sale trusts database location and never accepts client actor or destination',async()=>{const h=harness();const u=await redirected(h.load('../instruments/actions.ts').instrumentAction,{...sale,destination:id(5),branch:id(5),actor:id(5)});assert.deepEqual(h.calls.at(-1),{rpc:'move_instrument',args:{p_request:id(1),p_unit:id(2),p_kind:'SALE',p_destination:null,p_sale_price:'1200000',p_currency:'VND',p_warranty_until:null,p_reason:'Synthetic sale evidence'}});assert.equal(u.searchParams.get('unit'),id(2))})
test('instrument sale rejects negative or imprecise prices',async()=>{for(const price of ['-1','NaN','1.001','1000000000001']){const h=harness();await redirected(h.load('../instruments/actions.ts').instrumentAction,{...sale,price});assert.equal(h.calls.length,1)}})
test('instrument transfer omits monetary and warranty fields',async()=>{const h=harness();await redirected(h.load('../instruments/actions.ts').instrumentAction,{...sale,action:'TRANSFER',destination:id(4),warranty:'2027-01-01'});const a=h.calls.at(-1).args;assert.equal(a.p_destination,id(4));assert.equal(a.p_sale_price,null);assert.equal(a.p_currency,null);assert.equal(a.p_warranty_until,null)})
test('instrument receipt delegates trace identity and cost without ledger duplication',async()=>{const h=harness();await redirected(h.load('../instruments/actions.ts').instrumentAction,{action:'RECEIVE',request:id(1),model:id(2),branch:id(3),serial:'S-1',supplier:'Test',cost:'100',price:'120',currency:'VND',reason:'Receipt'});assert.equal(h.calls.at(-1).rpc,'receive_instrument');assert.equal(h.calls.at(-1).args.p_serial,'S-1');assert.equal(h.calls.filter(c=>c.rpc==='receive_instrument').length,1)})
