/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict')
const {harness,id,redirected}=require('./helpers/finance-operations.cjs')
const payload={action:'POST',request:id(1),item:id(2),branch:id(3),kind:'RECEIPT',quantity:'10',reason:'Counted receipt'}
test('inventory authenticates before mutation',async()=>{const h=harness({},null,false);const u=await redirected(h.load('../inventory/actions.ts').inventoryAction,payload);assert.equal(u.pathname,'/login');assert.equal(h.calls.length,1)})
test('inventory receipt delegates exact request to ledger and ignores actor and unused destination',async()=>{const h=harness();await redirected(h.load('../inventory/actions.ts').inventoryAction,{...payload,actor:id(5),destination:id(4)});assert.deepEqual(h.calls.at(-1),{rpc:'post_inventory_movement',args:{p_request:id(1),p_item:id(2),p_branch:id(3),p_destination:null,p_kind:'RECEIPT',p_quantity:'10',p_reason:'Counted receipt'}})})
test('inventory rejects invalid quantities without mutation',async()=>{for(const quantity of ['0','NaN','Infinity','1.0001','-1','1000000001']){const h=harness();const u=await redirected(h.load('../inventory/actions.ts').inventoryAction,{...payload,quantity});assert.equal(u.searchParams.get('error'),'invalid');assert.equal(h.calls.length,1)}})
test('inventory rejects transfer without distinct destination',async()=>{for(const destination of ['',id(3)]){const h=harness();await redirected(h.load('../inventory/actions.ts').inventoryAction,{...payload,kind:'TRANSFER',destination});assert.equal(h.calls.length,1)}})
test('inventory signed adjustment uses ledger with reason',async()=>{const h=harness();await redirected(h.load('../inventory/actions.ts').inventoryAction,{...payload,kind:'ADJUSTMENT',quantity:'-2'});assert.equal(h.calls.at(-1).args.p_quantity,'-2')})
test('stock posting returns to the actual branch and item',async()=>{const h=harness();const u=await redirected(h.load('../inventory/actions.ts').inventoryAction,payload);assert.equal(u.searchParams.get('branch'),id(3));assert.equal(u.searchParams.get('item'),id(2))})
test('catalogue normalizes code without accepting caller creator',async()=>{const h=harness();await redirected(h.load('../inventory/actions.ts').inventoryAction,{action:'CREATE',code:'book-1',name:'Book',category:'Books',unit:'copy',created_by:id(5)});assert.deepEqual(h.calls.at(-1),{rpc:'create_inventory_item',args:{p_code:'BOOK-1',p_name:'Book',p_category:'Books',p_unit:'copy'}})})
