/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict')
const {harness,id,render}=require('./helpers/finance-operations.cjs')
const route='../elearning/analytics'
function setup(error=null){const h=harness({learning_versions:[{id:id(2),title:'Synthetic version',version:1,state:'PUBLISHED'}]});const original=h.db.rpc;h.db.rpc=async(name,args)=>{if(name!=='learning_version_analytics')return original(name,args);h.calls.push({rpc:name,args});return {error,data:error?null:{title:'Synthetic version',version:1,state:'PUBLISHED',lessons:[{code:'TEST.L1',title:'Lesson',acknowledged_learners:2}],assessments:[{id:id(3),title:'Final',kind:'FINAL',policy_state:'APPROVED',attempts:3,learners:2,in_progress:1,pending_review:1,passed:0,failed:1,average_completed_score:25},{id:id(4),title:'Unattempted',kind:'PRACTICE',policy_state:'DRAFT',attempts:0,learners:0,in_progress:0,pending_review:0,passed:0,failed:0,average_completed_score:null}]}}};return h}
test('analytics distinguishes lesson acknowledgement, effective results and ungraded attempts',async()=>{const h=setup(),html=await render(h,route,{version:id(2)});assert.match(html,/không phải kết quả hoàn thành Academic/);assert.match(html,/3 lượt · 2 học viên/);assert.match(html,/Chờ chấm: 1/);assert.match(html,/Chưa đạt: 1/);assert.match(html,/25%/);assert.match(html,/Chưa có<\/p>/);assert.equal(h.calls.find(c=>c.rpc==='learning_version_analytics').args.p_version,id(2));assert.ok(!h.calls.some(c=>c.table==='learning_assessment_attempts'))})
test('analytics selects one version and bounds catalogue query',async()=>{const h=setup();await render(h,route,{page:'2'});assert.ok(!h.calls.some(c=>c.rpc==='learning_version_analytics'));assert.deepEqual(h.calls.find(c=>c.table==='learning_versions').range,[25,50])})
test('invalid version makes no analytics request',async()=>{const h=setup(),html=await render(h,route,{version:'forged'});assert.match(html,/Không tải được thống kê/);assert.ok(!h.calls.some(c=>c.rpc==='learning_version_analytics'))})
test('analytics error is visible without fabricated zero results',async()=>{const html=await render(setup({message:'unavailable'}),route,{version:id(2)});assert.match(html,/Không coi dữ liệu bị thiếu/);assert.doesNotMatch(html,/0 lượt/);assert.doesNotMatch(html,/unavailable/)})
test('analytics rejects non-admin before reading catalogue or RPC',async()=>{const h=harness({},null,false);await assert.rejects(()=>render(h,route,{version:id(2)}),e=>e.url.startsWith('/login'));assert.ok(!h.calls.some(c=>c.table||c.rpc==='learning_version_analytics'))})
