/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict')
const {harness,id,redirected,render}=require('./helpers/finance-operations.cjs')
const author='../elearning/assessments/actions.ts',learner='../../learn/assessments/actions.ts'
const valid={action:'CREATE',version:id(2),title:'Synthetic',kind:'FINAL',threshold:'70',points:'1',type:'TRUE_FALSE',mode:'AUTO',prompt:'Synthetic question',key:'true'}
test('assessment authoring denies non-admin before mutation',async()=>{const h=harness({},null,false);const url=await redirected(h.load(author).assessmentAdminAction,valid);assert.equal(url.pathname,'/login');assert.equal(h.calls.length,1)})
test('final authoring preserves approved limits and configured threshold',async()=>{const h=harness();await redirected(h.load(author).assessmentAdminAction,{...valid,threshold:'80',limit:'999',cooldown:'0'});assert.deepEqual(h.calls.at(-1).args,{p_version:id(2),p_title:'Synthetic',p_kind:'FINAL',p_threshold:80,p_limit:3,p_cooldown:86400,p_questions:[{code:'Q1',type:'TRUE_FALSE',mode:'AUTO',prompt:'Synthetic question',points:1,options:[],key:true}]})})
test('unsupported notation cannot be advertised as AUTO',async()=>{const h=harness();const u=await redirected(h.load(author).assessmentAdminAction,{...valid,type:'NOTE_PLACEMENT'});assert.equal(u.searchParams.get('error'),'manual');assert.equal(h.calls.length,1)})
test('approval never accepts forged reviewer identity',async()=>{const h=harness();await redirected(h.load(author).assessmentAdminAction,{action:'APPROVE',id:id(2),reason:'Reviewed',reviewer:id(9)});assert.deepEqual(h.calls.at(-1),{rpc:'approve_learning_assessment',args:{p_id:id(2),p_reason:'Reviewed'}})})
test('manual review sends marks not client-computed final score',async()=>{const h=harness();await redirected(h.load(author).assessmentAdminAction,{action:'REVIEW',id:id(2),'mark.Q1':'2',score:'100',reason:'Evidence checked'});assert.deepEqual(h.calls.at(-1),{rpc:'review_learning_assessment',args:{p_attempt:id(2),p_marks:{Q1:2},p_reason:'Evidence checked'}})})
test('anonymous student cannot start assessment',async()=>{const h=harness({},null,false,false);const u=await redirected(h.load(learner).startAssessment,{assessment:id(2),request:id(3),identity:'on'});assert.equal(u.pathname,'/login');assert.equal(h.calls.length,0)})
test('start uses canonical identity and attempt cap from database',async()=>{const h=harness();await redirected(h.load(learner).startAssessment,{assessment:id(2),request:id(3),identity:'on',student:id(9),limit:'999'});assert.deepEqual(h.calls.at(-1),{rpc:'start_learning_assessment',args:{p_id:id(2),p_request:id(3),p_identity_confirmed:true}})})
test('submission uses protected snapshot and ignores forged question type/score',async()=>{const h=harness({learning_assessment_attempts:[{id:id(2),question_snapshot:[{code:'Q1',type:'TRUE_FALSE',mode:'AUTO'}]}]});await redirected(h.load(learner).submitAssessment,{attempt:id(2),'answer.Q1':'false','answer.FORGED':'true',score:'100',student:id(9)});assert.deepEqual(h.calls.at(-1),{rpc:'submit_learning_assessment',args:{p_attempt:id(2),p_answers:{Q1:false}}})})
test('expiry preventing snapshot read prevents submission RPC',async()=>{const h=harness();const u=await redirected(h.load(learner).submitAssessment,{attempt:id(2),'answer.Q1':'true'});assert.equal(u.searchParams.get('error'),'assessment');assert.ok(!h.calls.some(c=>c.rpc==='submit_learning_assessment'))})
test('manual queue displays database overdue flag and private rubric to admin',async()=>{const h=harness({learning_assessments:[{id:id(3),questions:[{code:'Q1',rubric:'Synthetic rubric'}]}],learning_manual_review_queue:[{id:id(2),student_id:id(4),assessment_id:id(3),submitted_at:'2026-09-16T00:00:00Z',review_due_at:'2026-09-18T00:00:00Z',overdue:true,question_snapshot:[{code:'Q1',mode:'MANUAL',prompt:'Synthetic prompt',points:4}],answers:{Q1:'Response'}}]});const html=await render(h,'../elearning/assessments');assert.match(html,/Quá hạn, cần xử lý/);assert.match(html,/Synthetic rubric/);assert.ok(h.calls.some(c=>c.table==='learning_manual_review_queue'))})
