/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict')
const {harness,id,redirected,render}=require('./helpers/finance-operations.cjs')
test('notification action authenticates before mutation',async()=>{const h=harness({},null,false);const u=await redirected(h.load('../notifications/actions.ts').notificationAction,{action:'ENQUEUE',id:id(2),event:'ONBOARDING',channel:'IN_APP'});assert.equal(u.pathname,'/login');assert.equal(h.calls.length,1)})
test('enqueue ignores client payload recipient and mock mode',async()=>{const h=harness();const u=await redirected(h.load('../notifications/actions.ts').notificationAction,{action:'ENQUEUE',id:id(2),event:'LEARNING_REPORT',channel:'EMAIL',recipient:'attacker',payload:'private',mode:'MOCK'});assert.equal(u.searchParams.get('success'),'1');assert.deepEqual(h.calls.at(-1),{rpc:'enqueue_notification_event',args:{p_event:'LEARNING_REPORT',p_entity:id(2),p_channel:'EMAIL',p_mode:'LIVE'}})})
test('invalid notification action makes no mutation',async()=>{const h=harness();await redirected(h.load('../notifications/actions.ts').notificationAction,{action:'MARK_SENT',id:id(2)});assert.equal(h.calls.length,1)})
test('retry delegates state validation and does not create a new job',async()=>{const h=harness();await redirected(h.load('../notifications/actions.ts').notificationAction,{action:'RETRY',id:id(2)});assert.equal(h.calls.at(-1).rpc,'manage_notification');assert.equal(h.calls.at(-1).args.p_job,id(2))})
test('queue filters and pagination do not load full history',async()=>{const h=harness();await render(h,'../notifications',{status:'FAILED',channel:'EMAIL',page:'2'});const q=h.calls.find(c=>c.table==='notification_jobs');assert.deepEqual(q.range,[25,50]);assert.equal(q.filters.length,2);assert.ok(!q.fields.includes('payload'))})
test('mock queue is labeled and never offers live in-app delivery',async()=>{const h=harness({notification_jobs:[{id:id(2),recipient_id:id(3),channel:'IN_APP',delivery_mode:'MOCK',template_key:'ONBOARDING',status:'SENT',attempts:1,entity_type:'ONBOARDING',entity_id:id(3)}]});const html=await render(h,'../notifications');assert.match(html,/MOCK/);assert.doesNotMatch(html,/value="DELIVER"/);assert.match(html,/không phải gửi thật/)})
