const assert = require('node:assert/strict')
const fs = require('node:fs')

const page = fs.readFileSync('app/admin/hr/payslips/page.tsx', 'utf8')
const data = fs.readFileSync('app/admin/hr/payslips/data.ts', 'utf8')
const actions = fs.readFileSync('app/admin/hr/payslips/actions.ts', 'utf8')
const model = fs.readFileSync('app/admin/hr/payslips/model.ts', 'utf8')
const css = fs.readFileSync('app/admin/hr/payslips/payslips.module.css', 'utf8')

assert.match(page, /Phiếu lương &amp; chi trả/, 'page uses the required title')
for (const label of ['Kỳ lương', 'Chi nhánh', 'Trạng thái chi trả', 'Nhân viên / tìm kiếm', 'Bỏ lọc']) assert.ok(page.includes(label), `filter exists: ${label}`)
for (const field of ['Thực lĩnh', 'Đã chi', 'Còn lại', 'Xem phiếu lương →']) assert.ok(page.includes(field), `list field exists: ${field}`)
for (const state of ['NOT_PAID', 'PARTIALLY_PAID', 'PAID']) assert.ok(model.includes(state), `database-derived state modeled: ${state}`)
assert.match(data, /list_payroll_disbursements_v2/, 'list uses bounded database RPC')
assert.match(data, /get_payroll_disbursement_detail/, 'detail and payment history use database RPC')
assert.match(page, /detail\.can_record/, 'record form is permission and eligibility gated')
assert.match(page, /detail\.period\.status !== 'FINALIZED'/, 'APPROVED remains view-only')
assert.match(page, /detail\.payment_history/, 'payment history is visible')
assert.match(page, /payment\.status === 'CANCELLED'/, 'cancelled history remains visible')
assert.match(page, /Hủy ghi nhận trong hệ thống không đồng nghĩa hoàn tiền tại ngân hàng/, 'cancellation warning is explicit')
assert.match(actions, /record_payroll_disbursement/, 'record action uses dedicated RPC')
assert.match(actions, /cancel_payroll_disbursement/, 'cancel action uses dedicated RPC')
assert.match(actions, /Chưa xác nhận được kết quả ghi nhận/, 'uncertain write requires reconciliation')
assert.ok(!/Chưa có bằng chứng thanh toán/.test(page), 'static legacy payment badge removed')
assert.ok(!/Send email|Gửi email/.test(page), 'no fake email action')
assert.ok(!/type="file"|Chứng từ/.test(page), 'no payment upload field')
assert.ok(!/mock|demo|placeholder|localStorage/i.test(page), 'production page contains no demo state')
assert.ok(css.includes('var(--vibe-navy)') && css.includes('var(--vibe-line)'), 'Expense V2 visual tokens are reused')
assert.ok(!/from\(['"]payments['"]\)|record_payment/.test(actions), 'student tuition payment engine is not reused')

console.log('Payroll Disbursement V2 UI/action source contract: PASS')
