/* eslint-disable @typescript-eslint/no-require-imports */
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')

const navigation = fs.readFileSync('app/admin/navigation.ts', 'utf8')
const students = fs.readFileSync('app/admin/students/page.tsx', 'utf8')
const detail = fs.readFileSync('app/admin/business/registrations/[id]/page.tsx', 'utf8')
const crm = fs.readFileSync('app/admin/business/crm/[id]/page.tsx', 'utf8')
const migration = fs.readFileSync('supabase/migrations/20260922260000_registration_placement_v1.sql', 'utf8')

test('registration is a business route and students stay one menu item', () => {
  assert.match(navigation, /CRM & Tuyển sinh/)
  assert.match(navigation, /\/admin\/business\/registrations/)
  assert.equal(navigation.includes('waiting_students'), false)
  assert.equal((navigation.match(/name: 'Học viên'/g) || []).length, 1)
  assert.ok(fs.existsSync('app/admin/business/registrations/page.tsx'))
  assert.ok(fs.existsSync('app/admin/business/registrations/[id]/page.tsx'))
})

test('students page derives current and waiting without a second student table', () => {
  const shell = fs.readFileSync('app/admin/students/ops-shell.tsx', 'utf8')
  const hub = fs.readFileSync('app/admin/students/hub.tsx', 'utf8')
  const dashboard = fs.readFileSync('app/admin/_lib/dashboard-data.ts', 'utf8')
  assert.match(students, /Học viên đang hoạt động/)
  assert.equal(students.includes('Học viên hiện tại'), false)
  assert.equal(students.includes('Chờ sắp lớp'), false)
  assert.equal(students.includes('Xếp lớp'), false)
  assert.equal(students.includes('Chưa xếp lớp'), false)
  assert.equal(students.includes('Sắp lớp'), false)
  assert.match(shell, /Học viên đang hoạt động/)
  assert.match(shell, /Chờ vào ca dạy/)
  assert.match(students, /list_current_student_enrollments/)
  assert.match(students, /list_waiting_placements/)
  assert.match(students, /list_future_start_placements/)
  assert.match(students, /list_paused_student_enrollments/)
  assert.match(students, /count_current_student_enrollments/)
  assert.match(students, /count_waiting_placements/)
  assert.match(students, /count_future_start_placements/)
  assert.match(students, /count_paused_student_enrollments/)
  assert.match(students, /waiting_placement_summary/)
  assert.match(fs.readFileSync('app/admin/business/crm/model.ts', 'utf8'), /Đã vào ca dạy – chờ bắt đầu/)
  assert.match(students, /Sắp vào ca dạy/)
  assert.match(students, /Hành trình học thuật đã được ghi từ lúc đăng ký/)
  assert.match(students, /Đổi ca dạy/)
  assert.match(students, /Đang bảo lưu/)
  assert.match(students, /Chưa vào ca dạy/)
  assert.match(students, /Đang tìm ca phù hợp/)
  assert.equal(students.includes('placement_status}'), false)
  assert.equal(students.includes('waiting_students'), false)
  const movement = fs.readFileSync('app/admin/students/movement-data.ts', 'utf8')
  assert.match(movement, /count_current_student_enrollments/)
  assert.match(hub, /loadStudentMovement/)
  assert.equal(hub.includes(".eq('status', 'ACTIVE')"), false)
  assert.equal(movement.includes(".eq('status', 'ACTIVE')"), false)
  assert.match(dashboard, /count_current_student_enrollments/)
  assert.match(dashboard, /\/admin\/students\?tab=students/)
})

test('won lead can open a prefilled registration and completion stays reviewed', () => {
  assert.match(crm, /Bắt đầu đăng ký/)
  assert.match(crm, /registrations\/new\?lead=/)
  assert.match(detail, /Liên kết danh tính đã đối soát/)
  assert.match(migration, /REGISTRATION_REVIEW_REQUIRED/)
  assert.match(migration, /registration_invoice_settled/)
  assert.equal(migration.includes('waiting_students'), false)
})
