/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript')
const draft=require('../docs/elearning/drafts/grade1-pilot-v1.json'),source=require('../lib/learning/theory-contents.json'),blueprints=require('../lib/learning/theory-pilot-lessons.json')
const mod={exports:{}};new Function('module','exports',ts.transpileModule(fs.readFileSync('lib/learning/notation.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(mod,mod.exports)
const {parseNotation,notationText,measureDuration}=mod.exports
const lessons=draft.modules.flatMap(m=>m.lessons),questions=lessons.flatMap(l=>[...l.guided_practice,...l.independent_practice]).concat(draft.modules.flatMap(m=>m.checkpoint.questions))
test('pilot original draft stays unpublished without fabricated human approvals',()=>{assert.equal(draft.state,'DRAFT_REVIEW_ONLY');assert.equal(draft.published,false);assert.equal(draft.reviewer,null);assert.equal(draft.pedagogy_approval,null);assert.equal(draft.originality_approval,null);assert.equal(draft.integration_state,'NOT_IMPORTED_NO_LEARNER_DELIVERY');assert.equal(draft.source_sha256,source.source_sha256)})
test('draft retains five source modules and all twelve distinct lesson objectives',()=>{assert.deepEqual(draft.modules.map(m=>m.code),source.modules.slice(0,5).map(m=>m.code));assert.deepEqual(lessons.map(l=>l.code),blueprints.map(l=>l.code));for(const l of lessons){assert.equal(l.objective,blueprints.find(b=>b.code===l.code).objective);assert.ok(l.explanation.length>200);assert.ok(l.worked_steps.length>=3);assert.ok(l.misconception);assert.ok(l.summary.length>=3);assert.ok(l.guided_practice.length>=3&&l.guided_practice.length<=6);assert.ok(l.independent_practice.length>=5&&l.independent_practice.length<=12)}})
test('all original notation examples parse with exact rhythm and accessible alternatives',()=>{for(const l of lessons){const n=parseNotation(l.notation_example);assert.ok([2,3,4].includes(n.time.beats));assert.equal(n.time.unit,4);assert.ok(notationText(n).length>20);for(const m of n.measures){const d=measureDuration(m);assert.ok(d.n/d.d<=n.time.beats/n.time.unit)}}})
test('private draft questions have unique identities, real keys or manual rubrics, never fake automatic notation grades',()=>{assert.equal(questions.length,106);assert.equal(new Set(questions.map(q=>q.code)).size,106);for(const q of questions){assert.equal(q.review_state,'PENDING_PEDAGOGY_AND_ORIGINALITY');assert.equal(q.counts_toward_academic_progress,false);if(q.mode==='AUTO'){assert.equal(q.type,'SINGLE_CHOICE');assert.ok(q.options.includes(q.key));assert.equal(new Set(q.options).size,q.options.length)}else{assert.equal(q.mode,'MANUAL');assert.ok(q.rubric);assert.doesNotThrow(()=>parseNotation(q.reference_notation));assert.equal(q.key,undefined)}}})
test('checkpoint policies remain formative with explicit Grade 1 threshold',()=>{for(const m of draft.modules){assert.equal(m.checkpoint.kind,'CHECKPOINT');assert.equal(m.checkpoint.counts_toward_academic_progress,false);assert.equal(m.checkpoint.pass_threshold,70)}})
test('selected musical golden examples preserve middle C and two crotchet beats of semiquavers',()=>{const cross=lessons.find(l=>l.code==='MT1.04.L03').notation_example;assert.equal(cross.clef,'bass');assert.deepEqual(cross.measures[0].events[0].pitches,[{step:'C',octave:4,alter:0}]);const rhythm=lessons.find(l=>l.code==='MT1.05.L02').notation_example;assert.equal(rhythm.time.beats,2);assert.equal(rhythm.measures[0].events.length,8);assert.deepEqual(measureDuration(parseNotation(rhythm).measures[0]),{n:1,d:2});assert.deepEqual(rhythm.measures[0].beams.map(b=>b.length),[4,4])})
