/* eslint-disable @typescript-eslint/no-require-imports */
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs')
const {harness,id,redirected,render}=require('./helpers/finance-operations.cjs')
const lessons=require('../lib/learning/theory-pilot-lessons.json'),contents=require('../lib/learning/theory-contents.json')
const route='../elearning/theory/actions.ts'
function draft(codes=['MT1.01']){const f={level:id(2),version:'1',title:'Synthetic pilot',source:'Synthetic authoring fixture',module_codes:codes.join(',')};for(const l of lessons.filter(l=>codes.includes(l.module_code)))for(const section of ['explanation','worked','misconception','guided','independent','summary'])f[l.code+'.'+section]='Synthetic original '+section;return f}
test('pilot lesson blueprint preserves source lesson count and first five module order',()=>{assert.equal(lessons.length,12);assert.equal(new Set(lessons.map(l=>l.code)).size,12);assert.deepEqual(lessons.map(l=>l.code),['MT1.01.L01','MT1.01.L02','MT1.02.L01','MT1.02.L02','MT1.02.L03','MT1.03.L01','MT1.03.L02','MT1.04.L01','MT1.04.L02','MT1.04.L03','MT1.05.L01','MT1.05.L02']);assert.equal(lessons[4].title,'Complete bars');assert.equal(lessons[9].title,'Same pitch across clefs');assert.ok(lessons.every(l=>l.title!=='AUTO'&&!/^MT/.test(l.objective)));assert.deepEqual([...new Set(lessons.map(l=>l.module_code))],['MT1.01','MT1.02','MT1.03','MT1.04','MT1.05']);assert.ok(lessons.every(l=>l.objective&&l.title&&l.code.startsWith(l.module_code+'.L')));const migration=fs.readFileSync('supabase/migrations/20260917010000_learning_theory_contents_contract.sql','utf8');assert.ok(migration.includes(contents.source_sha256));for(const m of contents.modules)assert.ok(migration.includes("'"+m.code+"'"))})
test('pilot draft derives immutable catalogue metadata instead of caller titles and order',async()=>{const h=harness();await redirected(h.load(route).createTheoryPilot,{...draft(['MT1.02','MT1.01']),module_title:'forged',state:'PUBLISHED'});const rpc=h.calls.at(-1);assert.equal(rpc.rpc,'create_learning_version');const c=rpc.args.p_content;assert.equal(c.theory_grade,1);assert.equal(c.source_sha256,contents.source_sha256);assert.deepEqual(c.modules.map(m=>m.code),['MT1.01','MT1.02']);assert.equal(c.modules[0].title,contents.modules[0].title);assert.equal(c.modules[0].lessons.length,2);assert.equal(c.modules[1].lessons.length,3);assert.equal(c.modules[0].lessons[0].blocks.length,7);assert.equal(rpc.args.state,undefined)})
test('pilot cannot expand beyond approved first five or accept duplicate modules',async()=>{for(const module_codes of ['','MT1.06','MT5.15','MT1.01,MT1.01']){const h=harness();const u=await redirected(h.load(route).createTheoryPilot,{...draft(),module_codes});assert.equal(u.searchParams.get('error'),'invalid');assert.ok(!h.calls.some(c=>c.rpc==='create_learning_version'))}})
test('each lesson requires all authoring sections',async()=>{const h=harness(),f=draft();delete f['MT1.01.L02.worked'];const u=await redirected(h.load(route).createTheoryPilot,f);assert.equal(u.searchParams.get('error'),'invalid');assert.ok(!h.calls.some(c=>c.rpc==='create_learning_version'))})
test('unprivileged author cannot create theory draft',async()=>{const h=harness({},null,false);const u=await redirected(h.load(route).createTheoryPilot,draft());assert.equal(u.pathname,'/login')})
test('author page keeps missing source visible and only exposes numeric Grade 1 choices',async()=>{const h=harness({curriculums:[{id:id(3),name:'Programme',status:'ACTIVE'}],curriculum_levels:[{id:id(2),name:'Grade one',curriculum_id:id(3),status:'ACTIVE',level_type:'GRADE',level_number:1},{id:id(4),name:'Other Grade',curriculum_id:id(3),status:'ACTIVE',level_type:'GRADE',level_number:2}]});const html=await render(h,'../elearning/theory');assert.match(html,/Grade one/);assert.doesNotMatch(html,/Other Grade/);assert.match(html,/MT5.15/);assert.match(html,/Thiếu nguồn/);assert.match(html,/Lưu bản nháp pilot/)})
