const test=require('node:test'),assert=require('node:assert/strict')
const load=require('./helpers/zalo-module-loader.cjs')()
const {recoverRegistrationNotification}=load('lib/integrations/zalo/registration-recovery.ts')
const jobId='aa920000-0000-4000-8000-000000000081'
const env={ZALO_CREDENTIAL_OWNER:'main',ZALO_APP_ID:'123456789',ZALO_OA_ID:'987654321',ZALO_APP_SECRET:'synthetic'}
const parameters={customer_name:'Synthetic',student_name:'Synthetic',registration_code:'TEST',program_name:'Guitar',branch_name:'TEST',order_code:'TEST',payment_status:'Đã thanh toán đủ'}
function setup(){let consent=false,gate=false,attempts=0,state='BLOCKED',outbound=0,permission=true;const history=[];
 const view=()=>({jobId,applicationId:jobId,state,reason:!consent?'NO_CONSENT':!gate?'GATE_DISABLED':'CHANNEL_READY',attempts,orderCode:123,history:[...history]})
 const db={async rpc(name,a){if(name!=='zalo_registration_recovery')throw Error(name);if(!permission)return{error:{},data:null};if(a.p_action==='PREPARE'&&a.p_expected!==attempts)return{data:{...view(),state:'BLOCKED',reason:'STALE_ACTION'}};if(['CHECK','PREPARE'].includes(a.p_action)&&state==='BLOCKED'&&consent&&gate)state='SEND';return{data:view()}}}
 const admin={async rpc(name,a){
 if(name==='zalo_credential_command')return{data:{app_id:env.ZALO_APP_ID,oa_id:env.ZALO_OA_ID,version:1,state:'READY',access_token:'mock',refresh_token:'mock-refresh',expires_at:new Date(Date.now()+3600000).toISOString()}};
 if(name==='preview_zalo_dispatch_decision')return{data:{decision:['SEND','RETRY'].includes(state)?'SEND':'NOT_SENDABLE',job_id:jobId,provider_user_id:'84900000000',parameters,idempotency_key:'test',delivery_channel:'PHONE'}};
 if(name==='claim_zalo_registration_recovery'){if(a.p_expected!==attempts||!['SEND','RETRY'].includes(state))return{data:{state:'STALE_ACTION'}};state='UNCERTAIN';return{data:{state:'CLAIMED',jobId,attemptId:'attempt-'+attempts,phone:'84900000000',parameters}}}
 if(name==='start_zalo_recovery_outbound'){attempts++;return{data:'STARTED'}}
 if(name==='finish_zalo_registration_attempt'){state=a.p_state==='REJECTED'?'RETRY':a.p_state==='ACCEPTED'?'ACCEPTED':'UNCERTAIN';history.push({number:attempts,state:a.p_state,http:a.p_http,providerError:a.p_provider_error});return{data:a.p_state}}
 if(name==='block_zalo_registration_job')return{data:'BLOCKED'};throw Error(name)
 }};
 return{db,admin,correct(){consent=true;gate=true},deny(){permission=false},get count(){return outbound},get attempts(){return attempts},transport(error=0){return async()=>{outbound++;await new Promise(r=>setImmediate(r));return{status:200,json:async()=>error===0?{error:0,data:{msg_id:'mock-accepted'}}:{error}}}},input(action='CHECK',expectedAttempts=0){return{jobId,action,expectedAttempts}}}
}
test('blocked → consent/gate corrected → eligible → click → accepted; check never sends',async()=>{const x=setup();const run=(a='CHECK',n=0)=>recoverRegistrationNotification(x.db,x.admin,x.input(a,n),env,x.transport());assert.equal((await run()).state,'BLOCKED');assert.equal(x.count,0);x.correct();assert.equal((await run()).state,'SEND');assert.equal(x.attempts,0);assert.equal((await run('SEND')).state,'ACCEPTED');assert.equal(x.count,1);assert.equal((await run('CHECK',1)).state,'ACCEPTED');assert.equal(x.count,1)})
test('double clicks share CAS; replay after rejection cannot consume another attempt',async()=>{const x=setup();x.correct();await recoverRegistrationNotification(x.db,x.admin,x.input(),env);const send=()=>recoverRegistrationNotification(x.db,x.admin,x.input('SEND'),env,x.transport(-115));await Promise.all([send(),send()]);assert.equal(x.count,1);assert.equal(x.attempts,1);await send();assert.equal(x.count,1);const retry=await recoverRegistrationNotification(x.db,x.admin,x.input('SEND',1),env,x.transport());assert.equal(retry.state,'ACCEPTED');assert.equal(x.count,2)})
test('permissions fail before credential or network access',async()=>{const x=setup();x.correct();x.deny();const r=await recoverRegistrationNotification(x.db,{rpc(){throw Error('must not read credentials')}},x.input('SEND'),env,x.transport());assert.equal(r.reason,'RECOVERY_FORBIDDEN');assert.equal(x.count,0)})
test('unknown response remains protected; no resend or fabricated delivery',async()=>{const x=setup();x.correct();await recoverRegistrationNotification(x.db,x.admin,x.input(),env);let r=await recoverRegistrationNotification(x.db,x.admin,x.input('SEND'),env,x.transport(-99999));assert.equal(r.state,'UNCERTAIN');r=await recoverRegistrationNotification(x.db,x.admin,x.input('SEND',1),env,x.transport());assert.equal(r.state,'UNCERTAIN');assert.equal(x.count,1)})
test('shared OA ownership blocker never consumes send allowance',async()=>{const x=setup();x.correct();const r=await recoverRegistrationNotification(x.db,x.admin,x.input('SEND'),{},x.transport());assert.equal(r.state,'BLOCKED');assert.equal(r.connectionReason,'ZALO_OWNERSHIP_UNCONFIRMED');assert.equal(x.attempts,0);assert.equal(x.count,0)})
