const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript')
const cache=new Map()
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const m={exports:{}};cache.set(file,m.exports);new Function('module','exports','require',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m,m.exports,id=>id==='server-only'?{}:id.startsWith('.')?load(path.resolve(path.dirname(file),id+'.ts')):require(id));return m.exports}
const {getZaloCredential,readCredential,credentialCommand}=load('lib/integrations/zalo/oauth.ts')
const {sendZaloPhoneTemplate}=load('lib/integrations/zalo/phone.ts')
const {dispatchPreviewRegistrationZalo}=load('lib/integrations/zalo/preview-dispatch.ts')
const {verifyZaloToken}=load('lib/integrations/zalo/connection.ts')
const env={ZALO_CREDENTIAL_OWNER:'main',ZALO_APP_ID:'123456789',ZALO_OA_ID:'987654321',ZALO_APP_SECRET:'app-secret',ZALO_OA_ACCESS_TOKEN:'stale-env',ZALO_OA_REFRESH_TOKEN:'stale-refresh'}
const ready=()=>({app_id:env.ZALO_APP_ID,oa_id:env.ZALO_OA_ID,access_token:'access1',refresh_token:'refresh1',expires_at:new Date(Date.now()+9000000).toISOString(),state:'READY',version:1,operation_id:null})
const json=(body,status=200)=>({ok:status>=200&&status<300,status,json:async()=>body})
const provider=async(url)=>url.includes('/access_token')?json({access_token:'access2',refresh_token:'refresh2',expires_in:'90000'}):url.includes('/getoa')?json({error:0,data:{oa_id:env.ZALO_OA_ID}}):json({error:0,data:{}})
function store(initial=ready(),opts={}){
 let c=initial?{...initial}:null,calls=[]
 return {get c(){return c},calls,async rpc(name,a){calls.push([name,a]);if(name!=='zalo_credential_command')throw Error(name)
 if(a.p_action==='READ')return {data:c?{...c}:null,error:null}
 if(a.p_action==='BOOTSTRAP'){c??={...ready(),access_token:a.p_access,refresh_token:a.p_refresh,state:a.p_refresh?'NEEDS_REFRESH':'REAUTH_REQUIRED',error_code:a.p_refresh?null:'ZALO_REFRESH_TOKEN_MISSING',expires_at:null};return {data:{...c},error:null}}
 if(c.version!==a.p_version)return {data:{state:'STALE'},error:null}
 if(a.p_action==='CLAIM'){if(!['READY','NEEDS_REFRESH'].includes(c.state)||c.operation_id)return {data:{state:'BUSY_OR_BLOCKED'},error:null};c={...c,state:'REFRESHING',operation_id:a.p_operation,operation_started_at:new Date().toISOString()};return {data:{state:'CLAIMED'},error:null}}
 if(a.p_action==='BLOCK'){if(a.p_operation&&c.operation_id!==a.p_operation)return {data:{state:'STALE'},error:null};c={...c,state:a.p_error==='ZALO_REFRESH_UNCERTAIN'?'UNCERTAIN':a.p_error==='ZALO_PROOF_INVALID'?'PROOF_INVALID':a.p_error==='ZALO_TOKEN_INVALID'&&c.refresh_token?'NEEDS_REFRESH':'REAUTH_REQUIRED',error_code:a.p_error};return {data:{state:'BLOCKED'},error:null}}
 if(a.p_action==='COMMIT'){if(opts.failCommit)return {error:{},data:null};if(c.state!=='REFRESHING'||c.operation_id!==a.p_operation)return {data:{state:'STALE'},error:null};c={...c,access_token:a.p_access,refresh_token:a.p_refresh,expires_at:a.p_expires_at,version:c.version+1,state:'VERIFYING',committed_operation:a.p_operation,operation_id:null};if(opts.loseAck)return {data:null,error:{}};return {data:{state:'COMMITTED'},error:null}}
 if(a.p_action==='VERIFY'){if(c.state!=='VERIFYING')return {data:{state:'STALE'},error:null};c={...c,state:'READY'};return {data:{state:'VERIFIED'},error:null}}
 throw Error(a.p_action)
 }}
}
test('expired access rotates once, verifies OA, persists pair/expiry/version; restart ignores stale env',async()=>{const db=store({...ready(),expires_at:new Date(0).toISOString()});let rotations=0;const request=async(u,i)=>{if(u.includes('access_token')){rotations++;assert.equal(i.headers.secret_key,'app-secret');assert.equal(i.body.get('refresh_token'),'refresh1')}return provider(u,i)};const c=await getZaloCredential(db,env,request);assert.equal(c.access_token,'access2');assert.equal(c.version,2);assert.equal(c.refresh_token,'refresh2');assert.ok(Date.parse(c.expires_at)>Date.now());assert.equal((await getZaloCredential(db,env,async()=>{throw Error('must not call')})).access_token,'access2');assert.equal(rotations,1)})
test('missing refresh remains blocked without network or bootstrap overwrite',async()=>{const db=store(null);await assert.rejects(getZaloCredential(db,{...env,ZALO_OA_REFRESH_TOKEN:''},provider),/MISSING/);await assert.rejects(getZaloCredential(db,env,provider),/MISSING/);assert.equal(db.c.version,1)})
for(const error of [-14014,-14001])test('invalid/consumed refresh response '+error+' blocks reuse',async()=>{const db=store({...ready(),state:'NEEDS_REFRESH'});let calls=0;const request=async()=>{calls++;return json({error})};await assert.rejects(getZaloCredential(db,env,request),/RECONNECT/);await assert.rejects(getZaloCredential(db,env,request),/RECONNECT/);assert.equal(calls,1)})
test('two concurrent processes share claim; only one consumes refresh',async()=>{const db=store({...ready(),state:'NEEDS_REFRESH'});let release;const gate=new Promise(r=>release=r);let rotations=0;const request=async(u)=>{if(u.includes('access_token')){rotations++;await gate}return provider(u)};const first=getZaloCredential(db,env,request);await new Promise(r=>setImmediate(r));await assert.rejects(getZaloCredential(db,env,request,{waitAttempts:0}),/BUSY/);release();await first;assert.equal(rotations,1)})
test('refresh timeout is durable unknown and never consumes same refresh twice',async()=>{const db=store({...ready(),state:'NEEDS_REFRESH'});let calls=0;const request=async()=>{calls++;throw Error('timeout')};await assert.rejects(getZaloCredential(db,env,request),/UNCERTAIN/);await assert.rejects(getZaloCredential(db,env,request),/UNCERTAIN/);assert.equal(calls,1);assert.equal(db.c.state,'UNCERTAIN')})
test('rotation persistence failure blocks sends; no provider refresh retry',async()=>{const db=store({...ready(),state:'NEEDS_REFRESH'},{failCommit:true});let calls=0;await assert.rejects(getZaloCredential(db,env,async(u)=>{calls++;return provider(u)}),/UNCERTAIN/);assert.equal(calls,1);assert.equal(db.c.state,'UNCERTAIN');assert.equal(db.calls.filter(([,a])=>a.p_action==='COMMIT').length,2)})
test('lost commit acknowledgement recovered by readback without another rotation',async()=>{const db=store({...ready(),state:'NEEDS_REFRESH'},{loseAck:true});const c=await getZaloCredential(db,env,provider);assert.equal(c.access_token,'access2');assert.equal(c.state,'READY')})
test('crash after rotation persisted before verification resumes verification after restart',async()=>{const db=store({...ready(),state:'VERIFYING',version:2});let rotations=0;await getZaloCredential(db,env,async(u)=>{if(u.includes('access_token'))rotations++;return provider(u)});assert.equal(rotations,0);assert.equal(db.c.state,'READY')})
test('wrong OA after rotation stays blocked while recovered pair is retained',async()=>{const db=store({...ready(),state:'NEEDS_REFRESH'});await assert.rejects(getZaloCredential(db,env,async(u)=>u.includes('getoa')?json({error:0,data:{oa_id:'111111111'}}):provider(u)),/OA_MISMATCH/);assert.equal(db.c.access_token,'access2');assert.equal(db.c.state,'REAUTH_REQUIRED')})
test('late credential writer cannot overwrite a newer version',async()=>{const db=store({...ready(),version:8});assert.equal((await credentialCommand(db,env,'COMMIT',{p_version:7,p_access:'old'})).state,'STALE');assert.equal(db.c.version,8)})
const parameters={customer_name:'Synthetic Parent',registration_code:'DK-SYNTHETIC',student_name:'Synthetic Student',program_name:'Guitar',branch_name:'Synthetic Branch',order_code:'DK-SYNTHETIC',payment_status:'Đã thanh toán đủ'}
const message={jobId:'12345678-1234-1234-1234-123456789abc',phone:'84900000000',templateId:'640377',parameters,trackingId:'12345678123412341234123456789abc',registrationCompleted:true,allowlisted:true}
test('phone -1241 proof failure distinguished from invalid token; proof uses sent token',async()=>{for(const [code,state]of[[-1241,'ZALO_PROOF_INVALID'],[-124,'ZALO_TOKEN_INVALID'],[-115,'PROVIDER_REJECTED'],[-216,'AMBIGUOUS'],[-100,'AMBIGUOUS']]){const sent=await sendZaloPhoneTemplate(message,env,async(u,i)=>{assert.equal(i.headers.appsecret_proof,require('node:crypto').createHmac('sha256',env.ZALO_APP_SECRET).update(i.headers.access_token).digest('hex'));return json({error:code})});assert.equal(sent.state,state);assert.equal(sent.httpStatus,200)}})
function jobStore(opts={}) {const db=store();let status='QUEUED',sends=0,attempts=[],jobError=null;const rpc=db.rpc.bind(db);db.rpc=async(n,a)=>{
 if(n==='zalo_credential_command')return rpc(n,a)
 if(n==='preview_zalo_dispatch_decision')return {data:{decision:status==='QUEUED'?'SEND':status==='SENT'?'ALREADY_ACCEPTED':'NOT_SENDABLE',job_id:message.jobId,provider_user_id:message.phone,idempotency_key:'fixed',parameters,delivery_channel:'PHONE'},error:null}
 if(n==='authorize_zalo_registration_outbound')return {data:'STARTED',error:null}
 if(n==='claim_zalo_registration_attempt'){if(status!=='QUEUED')return {data:{state:'NOT_CLAIMED'},error:null};status='PROCESSING';attempts.push({id:'attempt'+attempts.length,state:'REQUESTING'});return {data:{state:'CLAIMED',attemptId:attempts.at(-1).id,jobId:message.jobId,phone:message.phone,parameters},error:null}}
 if(n==='finish_zalo_registration_attempt'){if(opts.failSave)return {data:null,error:{}};attempts.at(-1).state=a.p_state;status=a.p_state==='ACCEPTED'?'SENT':a.p_state==='REJECTED'?'FAILED':'ACCEPTANCE_UNKNOWN';return {data:a.p_state,error:null}}
 if(n==='block_zalo_registration_job'){jobError=a.p_error;return {data:'BLOCKED',error:null}}
 throw Error(n)
 };return {db,attempts,get status(){return status},retry(){assert.equal(status,'FAILED');assert.equal(attempts.at(-1).state,'REJECTED');status='QUEUED'}}}
test('definitive rejection then concurrent manual/worker recovery sends once and duplicate callback cannot resend',async()=>{const j=jobStore();let sends=0;assert.equal(await dispatchPreviewRegistrationZalo(j.db,1,async()=>{sends++;return json({error:-115})},env),'PROVIDER_REJECTED');j.retry();const out=await Promise.all([1,2].map(()=>dispatchPreviewRegistrationZalo(j.db,1,async()=>{sends++;return json({error:0,data:{msg_id:'msg2'}})},env)));assert.ok(out.includes('ACCEPTED'));assert.equal(sends,2);assert.equal(await dispatchPreviewRegistrationZalo(j.db,1,async()=>{throw Error('duplicate')},env),'ALREADY_ACCEPTED');assert.deepEqual(j.attempts.map(a=>a.state),['REJECTED','ACCEPTED'])})
for(const mode of ['timeout','accepted-write-failure'])test(mode+' never sends a second request',async()=>{const j=jobStore({failSave:mode==='accepted-write-failure'});let sends=0;const transport=async()=>{sends++;if(mode==='timeout')throw Error('timeout');return json({error:0,data:{msg_id:'accepted'}})};assert.equal(await dispatchPreviewRegistrationZalo(j.db,1,transport,env),'ZALO_ACCEPTANCE_UNKNOWN');await dispatchPreviewRegistrationZalo(j.db,1,transport,env);assert.equal(sends,1);assert.ok(['PROCESSING','ACCEPTANCE_UNKNOWN'].includes(j.status))})
test('known invalid authentication does not claim another send or consume retry count',async()=>{const j=jobStore();await dispatchPreviewRegistrationZalo(j.db,1,async()=>json({error:-124}),env);assert.equal(j.db.c.state,'NEEDS_REFRESH');j.retry();const out=await dispatchPreviewRegistrationZalo(j.db,1,async()=>{throw Error('no send')},env,async()=>json({error:-14014}));assert.equal(out,'ZALO_RECONNECT_REQUIRED');assert.equal(j.attempts.length,1)})

test('OA and ZBS diagnostics preserve separate proof/permission codes',async()=>{
 for(const [code,expected] of [[-242,'ZALO_PROOF_INVALID'],[-216,'ZALO_TOKEN_INVALID'],[-220,'ZALO_TOKEN_INVALID'],[-223,'ZALO_OA_PROVIDER_-223'],[-211,'ZALO_OA_PROVIDER_-211']]) {
  assert.equal(await verifyZaloToken('synthetic',env,async()=>json({error:code})),expected)
 }
 assert.equal(await verifyZaloToken('synthetic',env,async(url)=>url.includes('getoa')?json({error:0,data:{oa_id:env.ZALO_OA_ID}}):json({error:-1241})),'ZALO_PROOF_INVALID')
})

test('withdrawal after claim blocks transport without fabricating provider failure',async()=>{const j=jobStore();const rpc=j.db.rpc.bind(j.db);let sent=0,finished=0;j.db.rpc=async(n,a)=>{if(n==='authorize_zalo_registration_outbound')return{data:'NO_CONSENT'};if(n==='finish_zalo_registration_attempt')finished++;return rpc(n,a)};assert.equal(await dispatchPreviewRegistrationZalo(j.db,1,async()=>{sent++;return json({error:0})},env),'NO_CONSENT');assert.equal(sent,0);assert.equal(finished,0)})
