'use client'
import { useState, type ReactNode } from 'react'
import Link from 'next/link'
import type { IndexData } from './load'
import { formatMoney, statusLabels, timeText } from './model'
import { Modal } from './Dialog'
import styles from './payroll.module.css'
export default function PayrollIndex({ data, filters, createForm }: { data: IndexData; filters: Record<string, string | undefined>; createForm: ReactNode }) {
  const [open, setOpen] = useState(false)
  const pageHref = (page: number) => { const p = new URLSearchParams(); for (const name of ['month', 'branch', 'status']) if (filters[name]) p.set(name, filters[name]!); p.set('page', String(page)); return '/admin/payroll?' + p }
  return <div className={styles.root}>
    <nav className={styles.moduleNav} aria-label="Công và lương"><Link prefetch={false} href="/admin/payroll" aria-current="page">Kỳ lương</Link><Link prefetch={false} href="/admin/employees">Cấu hình nhân viên</Link><Link prefetch={false} href="/admin/employees/attendance">Chấm công nhân viên</Link></nav>
    <header className={styles.heading}><div className={styles.row}>{/* Keep the project's original logo asset, no embedded demo image. */}<img src="/vibe-logo.png" alt="VIBE Academy" className={styles.brand}/><div><div className={styles.eyebrow}>Không gian nhân sự / Công & Lương</div><h1>Kỳ lương</h1><p className={styles.sub}>Theo dõi bản đã tính, kiểm tra nguồn và xử lý từng kỳ.</p></div></div><button type="button" className={`${styles.btn} ${styles.primary}`} onClick={() => setOpen(true)}>+ Tạo kỳ lương</button></header>
    <form method="get" action="/admin/payroll" className={`${styles.card} ${styles.filters}`}><label className={styles.field}>Tháng<input name="month" type="month" defaultValue={filters.month || ''}/></label><label className={`${styles.field} ${styles.grow}`}>Chi nhánh<select name="branch" defaultValue={filters.branch || ''}><option value="">Tất cả chi nhánh</option>{data.branches.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className={styles.field}>Trạng thái<select name="status" defaultValue={filters.status || ''}><option value="">Tất cả trạng thái</option>{Object.entries(statusLabels).map(([id, text]) => <option key={id} value={id}>{text}</option>)}</select></label><button className={styles.btn} type="submit">Lọc kỳ lương</button><Link className={styles.btn} href="/admin/payroll" prefetch={false}>Bỏ lọc</Link></form>
    <div className={styles.alert} data-tone="info"><div className={styles.fill}><strong>Mẫu → Dữ liệu → Kết quả → Chi trả</strong><p>Số tiền bên dưới là tổng phải trả đã lưu, không phải doanh thu, không phải dự toán từ mẫu mới và không chứng minh tiền đã được chuyển.</p></div></div>
    <section className={styles.card}><div className={styles.cardhead}><div><h3>{data.count} kỳ phù hợp bộ lọc</h3><p className={styles.tiny}>Mở kỳ để xem bảng nhân viên, cấu hình và lịch sử.</p></div><span className={styles.tiny}>Hiển thị {data.rows.length} kỳ trên trang này</span></div><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Kỳ / lần tính gần nhất</th><th>Chi nhánh</th><th>Trạng thái</th><th className={styles.num}>Hồ sơ lương</th><th className={styles.num}>Thu nhập đã tính</th><th className={styles.num}>Khấu trừ</th><th className={styles.num}>Phải trả đã tính</th><th>Thao tác</th></tr></thead><tbody>{data.rows.length ? data.rows.map(row => <tr key={row.head.id}><td><Link className={styles.textBtn} prefetch={false} href={'/admin/payroll/' + row.head.id}>Tháng {row.head.starts_on.slice(0, 7).split('-').reverse().join('/')}</Link><div className={styles.tiny}>{timeText(row.head.generated_at)}</div></td><td>{row.branch}</td><td><span className={styles.tag} data-tone={['APPROVED', 'FINALIZED'].includes(row.head.status) ? 'green' : 'blue'}>{statusLabels[row.head.status] || row.head.status}</span>{row.head.status === 'DRAFT' && row.count > 0 && <div className={styles.tiny}>Còn bản tính trước đó</div>}</td><td className={styles.num}>{row.count}</td>{(['earnings', 'deductions', 'net'] as const).map(key => <td className={styles.num} key={key}>{row.currencyTotals.length ? row.currencyTotals.map(t => <div key={t.currency}>{key === 'net' ? <strong>{formatMoney(t[key], t.currency)}</strong> : formatMoney(t[key], t.currency)}</div>) : <span className={styles.tiny}>Chưa có bản tính</span>}</td>)}<td><Link className={styles.btn} prefetch={false} href={'/admin/payroll/' + row.head.id}>Mở kỳ →</Link></td></tr>) : <tr><td colSpan={8} className={styles.empty}>Chưa có kỳ lương phù hợp. Chọn lại bộ lọc hoặc tạo kỳ mới.</td></tr>}</tbody></table></div><div className={styles.tableFoot}><div className={styles.row}>{data.page > 1 && <Link className={styles.btn} prefetch={false} href={pageHref(data.page - 1)}>Trang trước</Link>}<span>Trang {data.page}</span>{data.more && <Link className={styles.btn} prefetch={false} href={pageHref(data.page + 1)}>Trang tiếp</Link>}</div><span>Các tiền tệ được trình bày riêng, không cộng chung.</span></div></section>
    <details className={styles.details}><summary>Cấu hình nhân viên và lịch sử theo cơ chế cũ</summary><p className={styles.note}>Cấu hình mới cho Payroll V2 nhập tại hồ sơ nhân viên. Lịch sử V1 vẫn giữ riêng để đối chiếu; không nhập lại một mức lương vào hai nguồn.</p><div className={styles.linkList}><Link prefetch={false} className={styles.btn} href="/admin/employees">Mở hồ sơ nhân viên</Link><Link prefetch={false} className={styles.btn} href="/admin/teachers">Hồ sơ giáo viên</Link></div></details>
    <footer className={styles.footer}><span>VIBE Academy · Công & Lương</span><span>Đợt 1 · Không tự tính lại hoặc sửa dữ liệu khi mở trang</span></footer>
    <Modal open={open} onClose={() => setOpen(false)} title="Tạo kỳ lương" subtitle="Chọn chi nhánh và tháng thực tế. Chưa tính hoặc chi lương ở bước này.">{createForm}</Modal>
  </div>
}
