'use client'
import { useMemo, useState } from 'react'
import { initialNotation, parseNotation, pitchText, type MusicMeasure, type Notation, type Pitch } from '../../../lib/learning/notation'
import NotationPreview from './NotationPreview'
const field='rounded border bg-white p-2 text-black',button='rounded border px-3 py-2'
export default function NotationEditor({name,initial=initialNotation}:{name:string;initial?:Notation}) {
  const [score,setScore]=useState<Notation>(initial),[selected,setSelected]=useState<string[]>([])
  const checked=useMemo(()=>{try{return {value:parseNotation(score),error:''}}catch(e){return {value:null,error:e instanceof Error?e.message:'Ký âm chưa hợp lệ.'}}},[score])
  const changeMeasure=(index:number,transform:(m:MusicMeasure)=>MusicMeasure)=>setScore(s=>({...s,measures:s.measures.map((m,i)=>i===index?transform(m):m)}))
  const group=(kind:'BEAM'|'TRIPLET'|'DUPLET'|'TIE'|'SLUR')=>{
    const ids=score.measures.flatMap(m=>m.events).filter(e=>selected.includes(e.id)).map(e=>e.id)
    const mi=score.measures.findIndex(m=>m.events.some(e=>e.id===ids[0]))
    if(mi<0)return
    if(kind==='TIE'||kind==='SLUR'){if(ids.length===2)setScore(s=>({...s,relations:[...s.relations,{kind,from:ids[0],to:ids[1]}]}));return}
    changeMeasure(mi,m=>kind==='BEAM'?{...m,beams:[...m.beams,ids]}:{...m,tuplets:[...m.tuplets,{ids,actual:kind==='TRIPLET'?3:2,normal:kind==='TRIPLET'?2:3}]})
  }
  const freshId=()=>{let n=1;const ids=new Set(score.measures.flatMap(m=>m.events.map(e=>e.id)));while(ids.has('n'+n))n++;return 'n'+n}
  return <div className="min-w-0 space-y-4"><p>Nhập cao độ, trường độ và nhóm ký hiệu. Có thể dùng bàn phím; hình ký âm có mô tả văn bản. Câu trả lời sẽ được chấm theo đề, không theo hình ảnh.</p>
    <input type="hidden" name={name} value={JSON.stringify(checked.value||score)}/>
    <div className="flex flex-wrap gap-3"><label>Khóa nhạc <select className={field} value={score.clef} onChange={e=>setScore(s=>({...s,clef:e.target.value as Notation['clef']}))}><option value="treble">Sol</option><option value="bass">Fa</option></select></label><label>Hóa biểu <select className={field} value={score.fifths} onChange={e=>setScore(s=>({...s,fifths:Number(e.target.value)}))}>{Array.from({length:15},(_,i)=>i-7).map(n=><option key={n} value={n}>{n===0?'Không':Math.abs(n)+(n<0?' giáng':' thăng')}</option>)}</select></label><label>Số phách <input className={field+' w-20'} type="number" min="1" max="12" value={score.time.beats} onChange={e=>setScore(s=>({...s,time:{...s.time,beats:Number(e.target.value)}}))}/></label><label>Đơn vị phách <select className={field} value={score.time.unit} onChange={e=>setScore(s=>({...s,time:{...s.time,unit:Number(e.target.value)}}))}>{[2,4,8,16].map(n=><option key={n}>{n}</option>)}</select></label></div>
    {score.measures.map((m,mi)=><fieldset key={mi} className="min-w-0 space-y-3 rounded border p-3"><legend>Ô nhịp {mi+1}</legend><label className="flex gap-2"><input type="checkbox" checked={m.partial} onChange={e=>changeMeasure(mi,m=>({...m,partial:e.target.checked}))}/>Chưa đầy đủ / lấy đà</label>
      {m.events.map((event,ei)=><div key={event.id} className="space-y-2 rounded border p-2"><div className="flex flex-wrap gap-2"><label className="flex items-center gap-2"><input type="checkbox" checked={selected.includes(event.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,event.id]:s.filter(v=>v!==event.id))}/>Chọn ký hiệu {ei+1}</label><label>Loại <select className={field} value={event.kind} onChange={e=>changeMeasure(mi,m=>({...m,events:m.events.map(v=>v.id!==event.id?v:{...v,kind:e.target.value as 'NOTE'|'REST',pitches:e.target.value==='REST'?[]:[{step:'C',octave:4,alter:0}]})}))}><option value="NOTE">Nốt</option><option value="REST">Lặng</option></select></label>
      <label>Trường độ <select className={field} value={event.denominator} onChange={e=>changeMeasure(mi,m=>({...m,events:m.events.map(v=>v.id===event.id?{...v,denominator:Number(e.target.value)}:v)}))}>{[1,2,4,8,16,32,64].map(n=><option key={n} value={n}>1/{n}</option>)}</select></label><label>Chấm dôi <select className={field} value={event.dots} onChange={e=>changeMeasure(mi,m=>({...m,events:m.events.map(v=>v.id===event.id?{...v,dots:Number(e.target.value)}:v)}))}>{[0,1,2].map(n=><option key={n}>{n}</option>)}</select></label><label>Hướng đuôi <select className={field} value={event.stem} onChange={e=>changeMeasure(mi,m=>({...m,events:m.events.map(v=>v.id===event.id?{...v,stem:e.target.value as typeof v.stem}:v)}))}><option value="AUTO">Tự động</option><option value="UP">Lên</option><option value="DOWN">Xuống</option></select></label></div>
      {event.pitches.map((pitch,pi)=><div key={pi} className="flex flex-wrap gap-2"><span>Cao độ {pi+1}</span><label>Tên nốt <select className={field} value={pitch.step} onChange={e=>changeMeasure(mi,m=>({...m,events:m.events.map(v=>v.id===event.id?{...v,pitches:v.pitches.map((p,j)=>j===pi?{...p,step:e.target.value as Pitch['step']}:p)}:v)}))}>{'CDEFGAB'.split('').map(n=><option key={n}>{n}</option>)}</select></label><label>Quãng tám <select className={field} value={pitch.octave} onChange={e=>changeMeasure(mi,m=>({...m,events:m.events.map(v=>v.id===event.id?{...v,pitches:v.pitches.map((p,j)=>j===pi?{...p,octave:Number(e.target.value)}:p)}:v)}))}>{Array.from({length:9},(_,n)=><option key={n}>{n}</option>)}</select></label><label>Dấu hóa <select className={field} value={pitch.alter} onChange={e=>changeMeasure(mi,m=>({...m,events:m.events.map(v=>v.id===event.id?{...v,pitches:v.pitches.map((p,j)=>j===pi?{...p,alter:Number(e.target.value)}:p)}:v)}))}>{[-2,-1,0,1,2].map((n,j)=><option key={n} value={n}>{['Giáng kép','Giáng','Bình','Thăng','Thăng kép'][j]}</option>)}</select></label>{event.pitches.length>1&&<button className={button} type="button" onClick={()=>changeMeasure(mi,m=>({...m,events:m.events.map(v=>v.id===event.id?{...v,pitches:v.pitches.filter((_,j)=>j!==pi)}:v)}))}>Bỏ cao độ {pi+1}</button>}</div>)}
      <div className="flex flex-wrap gap-2">{event.kind==='NOTE'&&event.pitches.length<6&&<button className={button} type="button" onClick={()=>{const p='CDEFGAB'.split('').map(step=>({step:step as Pitch['step'],octave:4,alter:0})).find(p=>!event.pitches.some(v=>pitchText(v)===pitchText(p)))!;changeMeasure(mi,m=>({...m,events:m.events.map(v=>v.id===event.id?{...v,pitches:[...v.pitches,p]}:v)}))}}>Thêm cao độ vào hợp âm</button>}{m.events.length>1&&<button className={button} type="button" onClick={()=>{changeMeasure(mi,m=>({...m,events:m.events.filter(v=>v.id!==event.id),beams:[],tuplets:[]}));setScore(s=>({...s,relations:s.relations.filter(r=>r.from!==event.id&&r.to!==event.id)}));setSelected(s=>s.filter(id=>id!==event.id))}}>Bỏ ký hiệu {ei+1}</button>}</div></div>)}
      {m.events.length<32&&<button className={button} type="button" onClick={()=>{const id=freshId();changeMeasure(mi,m=>({...m,events:[...m.events,{id,kind:'NOTE',pitches:[{step:'C',octave:4,alter:0}],denominator:4,dots:0,stem:'AUTO'}]}))}}>Thêm ký hiệu vào ô {mi+1}</button>}
    </fieldset>)}
    <div className="flex flex-wrap gap-2">{score.measures.length<8&&<button className={button} type="button" onClick={()=>{const id=freshId();setScore(s=>({...s,measures:[...s.measures,{partial:true,events:[{id,kind:'REST',pitches:[],denominator:4,dots:0,stem:'AUTO'}],beams:[],tuplets:[]}]}))}}>Thêm ô nhịp</button>}<button className={button} type="button" onClick={()=>group('BEAM')}>Nối cờ nhóm đã chọn</button><button className={button} type="button" onClick={()=>group('TRIPLET')}>Nhóm liên ba (3:2)</button><button className={button} type="button" onClick={()=>group('DUPLET')}>Nhóm liên hai (2:3)</button><button className={button} type="button" onClick={()=>group('TIE')}>Dấu nối hai nốt đã chọn</button><button className={button} type="button" onClick={()=>group('SLUR')}>Dấu luyến hai đầu đã chọn</button><button className={button} type="button" onClick={()=>setScore(s=>({...s,measures:s.measures.map(m=>({...m,beams:[],tuplets:[]})),relations:[]}))}>Bỏ nhóm và dấu nối/luyến</button></div>
    {checked.error?<p role="alert">Chưa thể nộp: {checked.error}</p>:checked.value&&<NotationPreview score={checked.value}/>}
  </div>
}
