import { randomUUID } from 'node:crypto'
import { assessmentStates, type DeliveredQuestion } from '../../../../lib/learning/question-types'
import { parseNotation } from '../../../../lib/learning/notation'
import NotationPreview from '../../../learn/components/NotationPreview'
import { assessmentAdminAction } from './actions'
type Result={id:string;student_id:string;assessment_id:string;state:string;score:number;revision_id:string|null;completed_at:string;answers:Record<string,unknown>;question_snapshot:DeliveredQuestion[];evidence:{code:string;points:number|null}[]}
function Answer({value}:{value:unknown}){
  let notation
  try { notation=parseNotation(value) } catch { notation=null }
  return notation ? <NotationPreview score={notation}/> : <p className="break-words">Trả lời: {JSON.stringify(value??null)}</p>
}
export default function GradingHistory({rows,policies}:{rows:Result[];policies:{id:string;title:string;questions:(DeliveredQuestion&{rubric?:string})[]}[]}){
  return <section className="space-y-3"><h2 className="text-xl font-semibold">25 kết quả gần nhất — chấm lại có lưu vết</h2><p>Chấm lại tạo sự kiện mới, giữ nguyên điểm gốc. Điểm tự động không được sửa bằng thao tác này; đáp án sai cần phiên bản đề mới.</p>{rows.map(a=><details key={a.id} className="rounded border p-4"><summary className="cursor-pointer break-words">{policies.find(p=>p.id===a.assessment_id)?.title||'Đề chưa tải được'} · {a.student_id} · {assessmentStates[a.state]} · {a.score}%</summary><p>Hoàn tất: {new Date(a.completed_at).toLocaleString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'})}</p>{a.question_snapshot.some(q=>q.mode!=='AUTO')?<form action={assessmentAdminAction} className="mt-3 space-y-3"><input type="hidden" name="action" value="REGRADE"/><input type="hidden" name="id" value={a.id}/><input type="hidden" name="request" value={randomUUID()}/><input type="hidden" name="revision" value={a.revision_id||''}/>{a.question_snapshot.filter(q=>q.mode!=='AUTO').map(q=><fieldset key={q.code} className="min-w-0 space-y-2 rounded border p-3"><legend className="whitespace-pre-wrap">{q.prompt}</legend><p className="whitespace-pre-wrap">Hướng dẫn chấm: {policies.find(p=>p.id===a.assessment_id)?.questions.find(item=>item.code===q.code)?.rubric||'Chưa tải được hướng dẫn — hãy tải lại trang trước khi chấm.'}</p><Answer value={a.answers?.[q.code]}/><label>Điểm sửa {q.code} / {q.points}<input className="block w-full rounded border p-2" type="number" name={'mark.'+q.code} min="0" max={q.points} step="0.01" required defaultValue={a.evidence.find(e=>e.code===q.code)?.points??0}/></label></fieldset>)}<label>Lý do và bằng chứng chấm lại<textarea className="block w-full rounded border p-2" name="reason" required maxLength={2000}/></label><button disabled={!policies.some(p=>p.id===a.assessment_id)} className="rounded border px-3 py-2 disabled:opacity-50">Ghi nhận chấm lại</button></form>:<p>Bài tự động hoàn toàn — không có điểm chấm tay để sửa.</p>}</details>)}</section>
}
