import Link from 'next/link'
import { adminClient, uuidPattern, pageNumber, type Params } from '../../../finance/operations'
import { rows } from '../../../finance/query'
import { period, payrollFields, money, type Payroll } from '../../data'
import { payrollAction } from '../../actions'
import { Panel, Table, Select, Field, LoadError, Pager } from '../../../finance/_components/ui'
import SubmitButton from '../../../finance/_components/SubmitButton'
export default async function TeacherPayroll({params,searchParams}:{params:Promise<{period:string;teacher:string}>;searchParams:Promise<Params>}) {
 const {period:id,teacher}=await params,p=await searchParams,page=pageNumber(p.page),db=await adminClient()
 if(!uuidPattern.test(teacher))return <p>Không tìm thấy nhân viên.</p>
 let head,t,loaded
 try {head=await period(db,id);[t]=await rows(db.from('teacher_payrolls').select(payrollFields).eq('period_id',id).or(`teacher_id.eq.${teacher},employee_id.eq.${teacher}`).returns<Payroll[]>())}catch{return <LoadError/>}
 if(!head||!t)return <p>Chưa có bảng lương.</p>
 try {loaded=await Promise.all([rows(db.from('payroll_earning_lines').select('id,session_id,earned_on,earning_type,duration_hours,rate,amount,duration_source,class_id,calculation_snapshot').eq('payroll_id',t.id).order('earned_on').order('id').range((page-1)*25,page*25)),rows(db.from('payroll_adjustments').select('id,kind,amount,reason,created_by,approved_by,payroll_trip_cost_breakdowns(allowance,transport,lodging)').eq('payroll_id',t.id).order('created_at').limit(100)),t.employee_id?rows(db.from('employee_trips').select('id,starts_on,ends_on,destination_unit,employee_trip_reviews!inner(decision)').eq('employee_id',t.employee_id).eq('employee_trip_reviews.decision','APPROVED').order('starts_on',{ascending:false}).limit(50)):Promise.resolve([]),t.employee_id?rows(db.from('payroll_earning_lines').select('calculation_snapshot').eq('payroll_id',t.id).eq('earning_type','MONTHLY_BASE')):Promise.resolve([])])}catch{return <LoadError/>}
 const [lines,adjustments,trips,monthly]=loaded
 const attendanceOptions=((monthly[0]?.calculation_snapshot?.sources||[]) as {attendance?:{id:string;work_date:string;shift_code:string;status:string}}[]).flatMap(s=>s.attendance&&['LATE','EARLY_LEAVE'].includes(s.attendance.status)?[{id:s.attendance.id,name:s.attendance.work_date+' '+s.attendance.shift_code+' — '+(s.attendance.status==='LATE'?'Đi muộn':'Về sớm')}]:[])
 return <div className="min-w-0 space-y-5"><Link prefetch={false} href={'/admin/payroll/'+id}>← Kỳ lương</Link><h1 className="text-3xl font-bold">{t.teacher_name}</h1><p>{t.pay_type} • {head.starts_on.slice(0,7)} • {head.status}</p><p>Lương tháng: {money(t.base_salary,t.currency)} • Giờ dạy: {t.teaching_hours} • Theo buổi / giờ: {money(t.hourly_earnings,t.currency)} • Điều chỉnh: {money(t.adjustment_amount,t.currency)}</p><p className="text-xl font-bold">Tổng: {money(t.gross_amount,t.currency)}</p>
 {['APPROVED','FINALIZED'].includes(head.status)&&<Link prefetch={false} href={'/documents/payslips/'+t.id}>Xem / In phiếu lương</Link>}{head.status==='FINALIZED'&&<Link prefetch={false} href={'/finance?payroll='+t.id}>Yêu cầu sửa sai lương đã chốt</Link>}<Panel title="Chi tiết thu nhập"><p>Lương tháng dựa trên phút lịch và chấm công đã duyệt. Lương giờ dùng thời lượng buổi học theo lịch; lương buổi dùng số buổi hoàn tất.</p><Table headers={['Ngày / buổi','Loại','Giờ','Mức áp dụng','Thành tiền','Căn cứ tính']} rows={lines.slice(0,25).map(l=>[l.session_id?<Link key={l.id} prefetch={false} href={'/admin/attendance/'+l.session_id}>{l.earned_on}</Link>:l.earned_on,l.earning_type,l.duration_hours,money(l.rate,t.currency),money(l.amount,t.currency),l.calculation_snapshot?.required_minutes!=null?`${l.calculation_snapshot.payable_minutes}/${l.calculation_snapshot.required_minutes} phút; ${l.calculation_snapshot.unpaid_minutes} phút không lương`:'—'])}/><Pager path={'/admin/payroll/'+id+'/'+teacher} params={p} page={page} more={lines.length>25}/></Panel>
 <Panel title="Các khoản điều chỉnh"><Table headers={['Loại','Số tiền','Lý do','Người tạo','Người duyệt','Chi phí']} rows={adjustments.map(a=>{const c=Array.isArray(a.payroll_trip_cost_breakdowns)?a.payroll_trip_cost_breakdowns[0]:a.payroll_trip_cost_breakdowns;return [a.kind,money(a.amount,t.currency),a.reason,a.created_by,a.approved_by||'Chưa duyệt',c?`Phụ cấp: ${money(c.allowance,t.currency)}; đi lại: ${money(c.transport,t.currency)}; lưu trú: ${money(c.lodging,t.currency)}`:'—']})}/>{['GENERATED','REVIEW'].includes(head.status)?<form action={payrollAction} className="space-y-3"><input type="hidden" name="action" value={t.employee_id?'evidence_adjust':'adjust'}/><input type="hidden" name="period" value={id}/><input type="hidden" name="payroll" value={t.id}/><Select name="kind" label="Loại điều chỉnh" options={[{id:'BONUS',name:'Thưởng'},{id:'DEDUCTION',name:'Khấu trừ'},{id:'CORRECTION',name:'Sửa sai'}]} required/><Field name="amount" label="Số tiền (âm nếu khấu trừ)"/><Field name="note" label="Lý do điều chỉnh"/>{t.employee_id&&<><input type="hidden" name="key" value={crypto.randomUUID()}/><Select name="attendance" label="Sự kiện đi muộn / về sớm" options={attendanceOptions} emptyLabel="Không áp dụng"/><p>Khấu trừ chỉ dựa trên sự kiện đã tính đủ công; không trừ lại thời gian vắng đã giảm lương cơ bản.</p></>}<SubmitButton>Thêm điều chỉnh</SubmitButton></form>:<p>Điều chỉnh đang khóa. Khoản thu nhập gốc không được sửa.</p>}</Panel>{t.employee_id&&['GENERATED','REVIEW'].includes(head.status)&&<Panel title="Công tác phí có chứng từ"><form action={payrollAction} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="action" value="trip_costs"/><input type="hidden" name="period" value={id}/><input type="hidden" name="payroll" value={t.id}/><input type="hidden" name="key" value={crypto.randomUUID()}/><Select name="trip" label="Chuyến công tác tính chi phí" options={trips.map(trip=>({id:trip.id,name:trip.starts_on+' → '+trip.ends_on+' — '+trip.destination_unit}))} required/><Field name="allowance" label="Phụ cấp" value="0"/><Field name="transport" label="Đi lại" value="0"/><Field name="lodging" label="Lưu trú" value="0"/><Field name="note" label="Lý do và tham chiếu chứng từ"/><SubmitButton>Thêm công tác phí</SubmitButton></form><p>Các khoản được cộng vào điều chỉnh và cần người khác duyệt cùng kỳ lương. Không tự động chi trả.</p></Panel>}</div>
}
