-- Remove unused client privileges without changing business RLS.
alter function public.has_role(text) set search_path=public,pg_temp;
alter function public.prepare_session_occurrence_identity() set search_path=public,pg_temp;
revoke execute on function public.prepare_session_occurrence_identity() from public,anon;
revoke execute on function public.prepare_session_occurrence_identity() from authenticated;
alter function public.validate_makeup_participant() set search_path=public,pg_temp;
revoke execute on function public.validate_makeup_participant() from public,anon;
revoke execute on function public.validate_makeup_participant() from authenticated;
alter function public.prevent_attended_makeup_participant_delete() set search_path=public,pg_temp;
revoke execute on function public.prevent_attended_makeup_participant_delete() from public,anon;
revoke execute on function public.prevent_attended_makeup_participant_delete() from authenticated;
alter function public.guard_makeup_credit_session_status() set search_path=public,pg_temp;
revoke execute on function public.guard_makeup_credit_session_status() from public,anon;
revoke execute on function public.guard_makeup_credit_session_status() from authenticated;
alter function public.guard_attendance_mutation_for_finalized_session() set search_path=public,pg_temp;
revoke execute on function public.guard_attendance_mutation_for_finalized_session() from public,anon;
revoke execute on function public.guard_attendance_mutation_for_finalized_session() from authenticated;
alter function public.guard_makeup_participant_identity_change() set search_path=public,pg_temp;
revoke execute on function public.guard_makeup_participant_identity_change() from public,anon;
revoke execute on function public.guard_makeup_participant_identity_change() from authenticated;
alter function public.reserve_makeup_credit_for_participant() set search_path=public,pg_temp;
revoke execute on function public.reserve_makeup_credit_for_participant() from public,anon;
revoke execute on function public.reserve_makeup_credit_for_participant() from authenticated;
alter function public.release_makeup_credit_for_removed_participant() set search_path=public,pg_temp;
revoke execute on function public.release_makeup_credit_for_removed_participant() from public,anon;
revoke execute on function public.release_makeup_credit_for_removed_participant() from authenticated;
alter function public.is_enrollment_paused_on(uuid,date) set search_path=public,pg_temp;
revoke execute on function public.is_enrollment_paused_on(uuid,date) from public,anon;
alter function public.validate_attendance_record_class() set search_path=public,pg_temp;
revoke execute on function public.validate_attendance_record_class() from public,anon;
revoke execute on function public.validate_attendance_record_class() from authenticated;
alter function public.start_student_academic_level(uuid,uuid,date) set search_path=public,pg_temp;
revoke execute on function public.start_student_academic_level(uuid,uuid,date) from public,anon;
alter function public.sync_subject_progress_from_components() set search_path=public,pg_temp;
revoke execute on function public.sync_subject_progress_from_components() from public,anon;
revoke execute on function public.sync_subject_progress_from_components() from authenticated;
alter function public.validate_session_occurrence_status() set search_path=public,pg_temp;
revoke execute on function public.validate_session_occurrence_status() from public,anon;
revoke execute on function public.validate_session_occurrence_status() from authenticated;
alter function public.sync_makeup_credits_from_session_status() set search_path=public,pg_temp;
revoke execute on function public.sync_makeup_credits_from_session_status() from public,anon;
revoke execute on function public.sync_makeup_credits_from_session_status() from authenticated;
alter function public.guard_enrollment_pause_change() set search_path=public,pg_temp;
revoke execute on function public.guard_enrollment_pause_change() from public,anon;
revoke execute on function public.guard_enrollment_pause_change() from authenticated;
alter function public.unlock_next_academic_level() set search_path=public,pg_temp;
revoke execute on function public.unlock_next_academic_level() from public,anon;
revoke execute on function public.unlock_next_academic_level() from authenticated;
alter function public.assign_student_academic_program(uuid,uuid,uuid,date,boolean) set search_path=public,pg_temp;
revoke execute on function public.assign_student_academic_program(uuid,uuid,uuid,date,boolean) from public,anon;
alter function public.sync_level_progress_from_subjects() set search_path=public,pg_temp;
revoke execute on function public.sync_level_progress_from_subjects() from public,anon;
revoke execute on function public.sync_level_progress_from_subjects() from authenticated;
alter function public.academic_grade_is_sealed(uuid) set search_path=public,pg_temp;
revoke execute on function public.academic_grade_is_sealed(uuid) from public,anon;
alter function public.guard_academic_level_integrity() set search_path=public,pg_temp;
revoke execute on function public.guard_academic_level_integrity() from public,anon;
revoke execute on function public.guard_academic_level_integrity() from authenticated;
alter function public.guard_academic_child_integrity() set search_path=public,pg_temp;
revoke execute on function public.guard_academic_child_integrity() from public,anon;
revoke execute on function public.guard_academic_child_integrity() from authenticated;
alter function public.guard_invoice_cancellation_with_payments() set search_path=public,pg_temp;
revoke execute on function public.guard_invoice_cancellation_with_payments() from public,anon;
revoke execute on function public.guard_invoice_cancellation_with_payments() from authenticated;
alter function public.guard_future_academic_progress() set search_path=public,pg_temp;
revoke execute on function public.guard_future_academic_progress() from public,anon;
revoke execute on function public.guard_future_academic_progress() from authenticated;
alter function public.update_student_academic_enrollment_start_date(uuid,date) set search_path=public,pg_temp;
revoke execute on function public.update_student_academic_enrollment_start_date(uuid,date) from public,anon;
alter function public.calculate_enrollment_tuition_effective_end(uuid) set search_path=public,pg_temp;
revoke execute on function public.calculate_enrollment_tuition_effective_end(uuid) from public,anon;
alter function public.recalculate_enrollment_tuition_effective_end(uuid) set search_path=public,pg_temp;
revoke execute on function public.recalculate_enrollment_tuition_effective_end(uuid) from public,anon;
alter function public.sync_enrollment_tuition_from_pause() set search_path=public,pg_temp;
revoke execute on function public.sync_enrollment_tuition_from_pause() from public,anon;
revoke execute on function public.sync_enrollment_tuition_from_pause() from authenticated;
alter function public.sync_new_enrollment_tuition_from_pauses() set search_path=public,pg_temp;
revoke execute on function public.sync_new_enrollment_tuition_from_pauses() from public,anon;
revoke execute on function public.sync_new_enrollment_tuition_from_pauses() from authenticated;
alter function public.guard_invoice_update() set search_path=public,pg_temp;
revoke execute on function public.guard_invoice_update() from public,anon;
revoke execute on function public.guard_invoice_update() from authenticated;
alter function public.guard_invoice_item_change() set search_path=public,pg_temp;
revoke execute on function public.guard_invoice_item_change() from public,anon;
revoke execute on function public.guard_invoice_item_change() from authenticated;
alter function public.create_tuition_invoice(uuid,text) set search_path=public,pg_temp;
revoke execute on function public.create_tuition_invoice(uuid,text) from public,anon;
alter function public.issue_invoice(uuid,date,date) set search_path=public,pg_temp;
revoke execute on function public.issue_invoice(uuid,date,date) from public,anon;
alter function public.cancel_invoice(uuid,text) set search_path=public,pg_temp;
revoke execute on function public.cancel_invoice(uuid,text) from public,anon;
alter function public.guard_payment_update() set search_path=public,pg_temp;
revoke execute on function public.guard_payment_update() from public,anon;
revoke execute on function public.guard_payment_update() from authenticated;
alter function public.guard_payment_allocation_change() set search_path=public,pg_temp;
revoke execute on function public.guard_payment_allocation_change() from public,anon;
revoke execute on function public.guard_payment_allocation_change() from authenticated;
alter function public.void_payment(uuid,text) set search_path=public,pg_temp;
revoke execute on function public.void_payment(uuid,text) from public,anon;
alter function public.create_payment(uuid,uuid,numeric,text,text,timestamp with time zone,text,text) set search_path=public,pg_temp;
revoke execute on function public.create_payment(uuid,uuid,numeric,text,text,timestamp with time zone,text,text) from public,anon;
alter function public.allocate_payment_to_invoice(uuid,uuid,numeric) set search_path=public,pg_temp;
revoke execute on function public.allocate_payment_to_invoice(uuid,uuid,numeric) from public,anon;
alter function public.guard_refund_update() set search_path=public,pg_temp;
revoke execute on function public.guard_refund_update() from public,anon;
revoke execute on function public.guard_refund_update() from authenticated;
alter function public.guard_refund_allocation_change() set search_path=public,pg_temp;
revoke execute on function public.guard_refund_allocation_change() from public,anon;
revoke execute on function public.guard_refund_allocation_change() from authenticated;
alter function public.allocate_refund_to_payment_allocation(uuid,uuid,numeric) set search_path=public,pg_temp;
revoke execute on function public.allocate_refund_to_payment_allocation(uuid,uuid,numeric) from public,anon;
alter function public.create_refund(uuid,numeric,timestamp with time zone,text,text) set search_path=public,pg_temp;
revoke execute on function public.create_refund(uuid,numeric,timestamp with time zone,text,text) from public,anon;
alter function public.void_refund(uuid,text) set search_path=public,pg_temp;
revoke execute on function public.void_refund(uuid,text) from public,anon;
alter function public.update_tuition_discount(uuid,text,numeric,text) set search_path=public,pg_temp;
revoke execute on function public.update_tuition_discount(uuid,text,numeric,text) from public,anon;
alter function public.preview_tuition_discount(uuid,text,numeric,text) set search_path=public,pg_temp;
revoke execute on function public.preview_tuition_discount(uuid,text,numeric,text) from public,anon;
alter function public.preview_tuition_term(uuid,uuid,date,text,numeric,text) set search_path=public,pg_temp;
revoke execute on function public.preview_tuition_term(uuid,uuid,date,text,numeric,text) from public,anon;
alter function public.create_tuition_term(uuid,uuid,date,text,numeric,text,text) set search_path=public,pg_temp;
revoke execute on function public.create_tuition_term(uuid,uuid,date,text,numeric,text,text) from public,anon;
alter function public.resolve_tuition_reminder(uuid,text,text) set search_path=public,pg_temp;
revoke execute on function public.resolve_tuition_reminder(uuid,text,text) from public,anon;
alter function public.invalidate_tuition_reminders() set search_path=public,pg_temp;
revoke execute on function public.invalidate_tuition_reminders() from public,anon;
revoke execute on function public.invalidate_tuition_reminders() from authenticated;
alter function public.generate_tuition_reminders() set search_path=public,pg_temp;
revoke execute on function public.generate_tuition_reminders() from public,anon;
alter function public.generate_learning_report(uuid,text,date,date) set search_path=public,pg_temp;
revoke execute on function public.generate_learning_report(uuid,text,date,date) from public,anon;
alter function public.learning_report_source(uuid,date,date) set search_path=public,pg_temp;
revoke execute on function public.learning_report_source(uuid,date,date) from public,anon;
alter function public.update_learning_report(uuid,integer,text,jsonb,text) set search_path=public,pg_temp;
revoke execute on function public.update_learning_report(uuid,integer,text,jsonb,text) from public,anon;
alter function public.resolve_lesson_feedback(uuid,integer,text,text) set search_path=public,pg_temp;
revoke execute on function public.resolve_lesson_feedback(uuid,integer,text,text) from public,anon;
alter function public.capture_session_teacher() set search_path=public,pg_temp;
revoke execute on function public.capture_session_teacher() from public,anon;
revoke execute on function public.capture_session_teacher() from authenticated;
alter function public.set_session_teacher(uuid,uuid,text,text) set search_path=public,pg_temp;
revoke execute on function public.set_session_teacher(uuid,uuid,text,text) from public,anon;
alter function public.submit_lesson_feedback(uuid,uuid,text,integer,integer,integer,integer,text) set search_path=public,pg_temp;
revoke execute on function public.submit_lesson_feedback(uuid,uuid,text,integer,integer,integer,integer,text) from public,anon;
alter function public.can_read_payroll_period(uuid) set search_path=public,pg_temp;
revoke execute on function public.can_read_payroll_period(uuid) from public,anon;
alter function public.add_compensation_rule(uuid,uuid,text,numeric,text,date,date) set search_path=public,pg_temp;
revoke execute on function public.add_compensation_rule(uuid,uuid,text,numeric,text,date,date) from public,anon;
alter function public.create_payroll_period(uuid,date) set search_path=public,pg_temp;
revoke execute on function public.create_payroll_period(uuid,date) from public,anon;
alter function public.generate_teacher_payroll(uuid) set search_path=public,pg_temp;
revoke execute on function public.generate_teacher_payroll(uuid) from public,anon;
alter function public.add_payroll_adjustment(uuid,text,numeric,text) set search_path=public,pg_temp;
revoke execute on function public.add_payroll_adjustment(uuid,text,numeric,text) from public,anon;
alter function public.transition_payroll(uuid,integer,text,text) set search_path=public,pg_temp;
revoke execute on function public.transition_payroll(uuid,integer,text,text) from public,anon;
revoke truncate on public.tuition_reminders from anon,authenticated;
revoke truncate on public.learning_reports from anon,authenticated;
revoke truncate on public.learning_report_events from anon,authenticated;
revoke truncate on public.session_teacher_assignments from anon,authenticated;
revoke truncate on public.session_teacher_snapshots from anon,authenticated;
revoke truncate on public.lesson_feedback from anon,authenticated;
revoke truncate on public.lesson_feedback_events from anon,authenticated;
revoke truncate on public.branches from anon,authenticated;
revoke truncate on public.teacher_compensation_rules from anon,authenticated;
revoke truncate on public.curriculum_levels from anon,authenticated;
revoke truncate on public.payroll_periods from anon,authenticated;
revoke truncate on public.curriculum_subject_components from anon,authenticated;
revoke truncate on public.teacher_payrolls from anon,authenticated;
revoke truncate on public.curriculum_subjects from anon,authenticated;
revoke truncate on public.payroll_earning_lines from anon,authenticated;
revoke truncate on public.curriculums from anon,authenticated;
revoke truncate on public.payroll_adjustments from anon,authenticated;
revoke truncate on public.parents from anon,authenticated;
revoke truncate on public.payroll_events from anon,authenticated;
revoke truncate on public.permissions from anon,authenticated;
revoke truncate on public.profiles from anon,authenticated;
revoke truncate on public.role_permissions from anon,authenticated;
revoke truncate on public.roles from anon,authenticated;
revoke truncate on public.student_component_progress from anon,authenticated;
revoke truncate on public.student_curriculum_enrollments from anon,authenticated;
revoke truncate on public.student_level_progress from anon,authenticated;
revoke truncate on public.student_parents from anon,authenticated;
revoke truncate on public.student_subject_progress from anon,authenticated;
revoke truncate on public.students from anon,authenticated;
revoke truncate on public.teacher_branches from anon,authenticated;
revoke truncate on public.user_roles from anon,authenticated;
revoke truncate on public.teachers from anon,authenticated;
revoke truncate on public.courses from anon,authenticated;
revoke truncate on public.classes from anon,authenticated;
revoke truncate on public.class_teachers from anon,authenticated;
revoke truncate on public.enrollments from anon,authenticated;
revoke truncate on public.rooms from anon,authenticated;
revoke truncate on public.schedules from anon,authenticated;
revoke truncate on public.attendance_records from anon,authenticated;
revoke truncate on public.session_occurrences from anon,authenticated;
revoke truncate on public.makeup_credits from anon,authenticated;
revoke truncate on public.session_occurrence_participants from anon,authenticated;
revoke truncate on public.learning_journals from anon,authenticated;
revoke truncate on public.enrollment_pauses from anon,authenticated;
revoke truncate on public.tuition_plans from anon,authenticated;
revoke truncate on public.enrollment_tuition from anon,authenticated;
revoke truncate on public.tuition_plan_branch_prices from anon,authenticated;
revoke truncate on public.invoices from anon,authenticated;
revoke truncate on public.invoice_items from anon,authenticated;
revoke truncate on public.payments from anon,authenticated;
revoke truncate on public.payment_allocations from anon,authenticated;
revoke truncate on public.refunds from anon,authenticated;
revoke truncate on public.refund_allocations from anon,authenticated;
revoke insert,update,delete on public.invoices from anon,authenticated;
revoke insert,update,delete on public.invoice_items from anon,authenticated;
revoke insert,update,delete on public.payments from anon,authenticated;
revoke insert,update,delete on public.payment_allocations from anon,authenticated;
revoke insert,update,delete on public.refunds from anon,authenticated;
revoke insert,update,delete on public.refund_allocations from anon,authenticated;
