-- Remove unintended platform default privileges without changing business roles or permissions.
begin;
alter function public.academic_operation_actor() set search_path = public, pg_temp;
alter function public.academic_ops_may_manage() set search_path = public, pg_temp;
alter function public.book_makeup_seat(uuid,uuid,text) set search_path = public, pg_temp;
alter function public.cancel_active_pause(uuid,text) set search_path = public, pg_temp;
alter function public.cancel_makeup_booking(uuid,text) set search_path = public, pg_temp;
alter function public.confirm_absence(uuid,boolean,text) set search_path = public, pg_temp;
alter function public.correct_source_attendance(uuid,text,text) set search_path = public, pg_temp;
alter function public.current_academic_operation_policy() set search_path = public, pg_temp;
alter function public.decide_enrollment_pause(uuid,boolean,text) set search_path = public, pg_temp;
alter function public.generate_tuition_reminders() set search_path = public, pg_temp;
alter function public.mark_makeup_credit_from_attendance() set search_path = public, pg_temp;
alter function public.pause_makeup_desk(text,text,text,integer) set search_path = public, pg_temp;
alter function public.pause_makeup_reconcile_report() set search_path = public, pg_temp;
alter function public.preview_enrollment_pause(uuid,date,date) set search_path = public, pg_temp;
alter function public.release_completed_makeup_without_present(uuid,text) set search_path = public, pg_temp;
alter function public.replace_approved_pause_end(uuid,date,text) set search_path = public, pg_temp;
alter function public.report_absence(uuid,text) set search_path = public, pg_temp;
alter function public.request_enrollment_pause(uuid,date,date,text) set search_path = public, pg_temp;
alter function public.reserve_makeup_credit_for_participant() set search_path = public, pg_temp;
alter function public.restore_enrollment_shift(uuid,uuid,date,text,text) set search_path = public, pg_temp;
alter function public.sync_makeup_credits_from_session_status() set search_path = public, pg_temp;
revoke execute on function public.academic_operation_actor() from public, anon;
revoke execute on function public.academic_ops_may_manage() from public, anon;
revoke execute on function public.book_makeup_seat(uuid,uuid,text) from public, anon;
revoke execute on function public.cancel_active_pause(uuid,text) from public, anon;
revoke execute on function public.cancel_makeup_booking(uuid,text) from public, anon;
revoke execute on function public.confirm_absence(uuid,boolean,text) from public, anon;
revoke execute on function public.correct_source_attendance(uuid,text,text) from public, anon;
revoke execute on function public.current_academic_operation_policy() from public, anon;
revoke execute on function public.decide_enrollment_pause(uuid,boolean,text) from public, anon;
revoke execute on function public.mark_makeup_credit_from_attendance() from public, anon;
revoke execute on function public.pause_makeup_desk(text,text,text,integer) from public, anon;
revoke execute on function public.pause_makeup_reconcile_report() from public, anon;
revoke execute on function public.preview_enrollment_pause(uuid,date,date) from public, anon;
revoke execute on function public.release_completed_makeup_without_present(uuid,text) from public, anon;
revoke execute on function public.replace_approved_pause_end(uuid,date,text) from public, anon;
revoke execute on function public.report_absence(uuid,text) from public, anon;
revoke execute on function public.request_enrollment_pause(uuid,date,date,text) from public, anon;
revoke execute on function public.restore_enrollment_shift(uuid,uuid,date,text,text) from public, anon;
revoke truncate on table public.absence_reports from public, anon, authenticated;
revoke truncate on table public.academic_operation_exceptions from public, anon, authenticated;
revoke truncate on table public.academic_operation_policies from public, anon, authenticated;
revoke truncate on table public.enrollment_pause_events from public, anon, authenticated;
revoke truncate on table public.enrollment_pause_requests from public, anon, authenticated;
revoke truncate on table public.enrollment_shift_changes from public, anon, authenticated;
notify pgrst, 'reload schema';
commit;
